/* Keyboard — the voice bank.
 *
 * AUDIO-DIRECTION.md decision 6: instruments are runtime WebAudio synthesis.
 * No sample sets, no audio files, nothing to download. Every voice below is
 * built from oscillators, gains, filters and envelopes. The one buffer in
 * this file is white noise generated by Math.random() the first time a drum
 * is struck — made on the device, never fetched, so nothing ships with it.
 *
 * A voice is a function (a, m) -> { gated, stop(pedal) }
 *   a.ctx   the AudioContext
 *   a.dest  the node to play into (the master gain)
 *   a.t     the moment the note starts, on the audio clock
 *   m       the MIDI note number
 *   gated   true when the voice holds a steady level until it is stopped
 *           (organ, strings); false when it decays on its own (piano, bells)
 *   stop(pedal)  release. With the pedal down a gated voice keeps ringing a
 *           little and a decaying one is left to decay; with the pedal up
 *           both are damped.
 *
 * A drum is a function (a) -> void. One shot, no handle: it finishes itself.
 */
(function () {
  "use strict";

  const KB = (window.KB = window.KB || {});

  const FREQ = (m) => 440 * Math.pow(2, (m - 69) / 12);

  /* One noise buffer per context, generated on first use. Two seconds of
     white noise is enough for any drum here and small enough not to matter. */
  function noise(a) {
    if (!a.ctx._kbNoise) {
      const len = Math.floor(a.ctx.sampleRate * 2);
      const buf = a.ctx.createBuffer(1, len, a.ctx.sampleRate);
      const d = buf.getChannelData(0);
      for (let i = 0; i < len; i += 1) d[i] = Math.random() * 2 - 1;
      a.ctx._kbNoise = buf;
    }
    const src = a.ctx.createBufferSource();
    src.buffer = a.ctx._kbNoise;
    src.loop = true;
    return src;
  }

  /* ------------------------------------------------- the original four ---
     Ported unchanged from the single-file app: same oscillators, same
     envelopes, same numbers. Classic must sound exactly as it did. */

  function piano(a, m) {
    const f = FREQ(m);
    const { ctx, t } = a;
    const out = ctx.createGain();
    const lp = ctx.createBiquadFilter();
    lp.type = "lowpass";
    lp.frequency.setValueAtTime(Math.min(f * 8, 9000), t);
    lp.frequency.exponentialRampToValueAtTime(Math.max(f * 1.6, 500), t + 1.1);
    out.connect(lp);
    lp.connect(a.dest);

    const parts = [
      [1, 0.5, "triangle"], [2.001, 0.14, "sine"], [3.003, 0.05, "sine"],
    ];
    const oscs = parts.map(([mult, g, type], i) => {
      const o = ctx.createOscillator();
      o.type = type;
      o.frequency.value = f * mult;
      o.detune.value = i === 0 ? 0 : (i === 1 ? 2 : -3);
      const og = ctx.createGain();
      og.gain.value = g;
      o.connect(og);
      og.connect(out);
      o.start(t);
      return o;
    });
    /* Higher notes ring shorter, as strings do. */
    const decay = Math.max(0.7, 3.4 - (m - 48) * 0.045);
    out.gain.setValueAtTime(0.0001, t);
    out.gain.exponentialRampToValueAtTime(1, t + 0.004);
    out.gain.setTargetAtTime(0.12, t + 0.004, 0.16);
    out.gain.setTargetAtTime(0.0001, t + 0.1, decay / 3);
    return {
      gated: false,
      stop(pedal) {
        const s = a.now() + 0.01;
        out.gain.cancelScheduledValues(s);
        out.gain.setTargetAtTime(0.0001, s, pedal ? 0.35 : 0.06);
        oscs.forEach((o) => o.stop(s + (pedal ? 1.4 : 0.4)));
      },
    };
  }

  function epiano(a, m) {
    const f = FREQ(m);
    const { ctx, t } = a;
    const out = ctx.createGain();
    out.connect(a.dest);

    /* A tine piano is close to one sine "carrier" whose frequency is nudged
       by a second sine "tine" — classic FM, three nodes, bell-like attack. */
    const carrier = ctx.createOscillator();
    carrier.type = "sine";
    carrier.frequency.value = f;
    const tine = ctx.createOscillator();
    tine.type = "sine";
    tine.frequency.value = f * 3.987;
    const mod = ctx.createGain();
    mod.gain.setValueAtTime(f * 2.4, t);
    mod.gain.exponentialRampToValueAtTime(f * 0.02, t + 0.5);
    tine.connect(mod);
    mod.connect(carrier.frequency);

    const strike = ctx.createOscillator();
    strike.type = "sine";
    strike.frequency.value = f * 2;
    const strikeGain = ctx.createGain();
    strikeGain.gain.setValueAtTime(0.18, t);
    strikeGain.gain.exponentialRampToValueAtTime(0.0001, t + 0.18);
    strike.connect(strikeGain);
    strikeGain.connect(out);

    carrier.connect(out);
    carrier.start(t); tine.start(t); strike.start(t);
    strike.stop(t + 0.3);
    const decay = Math.max(0.9, 4 - (m - 48) * 0.05);
    out.gain.setValueAtTime(0.0001, t);
    out.gain.exponentialRampToValueAtTime(0.9, t + 0.003);
    out.gain.setTargetAtTime(0.0001, t + 0.05, decay / 3);
    return {
      gated: false,
      stop(pedal) {
        const s = a.now() + 0.01;
        out.gain.cancelScheduledValues(s);
        out.gain.setTargetAtTime(0.0001, s, pedal ? 0.4 : 0.07);
        carrier.stop(s + (pedal ? 1.6 : 0.5));
        tine.stop(s + (pedal ? 1.6 : 0.5));
      },
    };
  }

  function organ(a, m) {
    const f = FREQ(m);
    const { ctx, t } = a;
    const out = ctx.createGain();
    out.connect(a.dest);
    /* Drawbars: fundamental plus three harmonics, one slightly detuned pair
       for the shimmer a spinning speaker gives. Sustains while held. */
    const bars = [
      [0.5, 0.12], [1, 0.42], [1.001, 0.3], [2, 0.2], [3, 0.09], [4, 0.05],
    ];
    const oscs = bars.map(([mult, g]) => {
      const o = ctx.createOscillator();
      o.type = "sine";
      o.frequency.value = f * mult;
      const og = ctx.createGain();
      og.gain.value = g;
      o.connect(og);
      og.connect(out);
      o.start(t);
      return o;
    });
    out.gain.setValueAtTime(0.0001, t);
    out.gain.exponentialRampToValueAtTime(0.5, t + 0.02);
    return {
      gated: true,
      stop(pedal) {
        const s = a.now() + 0.01;
        out.gain.cancelScheduledValues(s);
        out.gain.setTargetAtTime(0.0001, s, pedal ? 0.3 : 0.05);
        oscs.forEach((o) => o.stop(s + (pedal ? 1.2 : 0.3)));
      },
    };
  }

  function synth(a, m) {
    const f = FREQ(m);
    const { ctx, t } = a;
    const out = ctx.createGain();
    const lp = ctx.createBiquadFilter();
    lp.type = "lowpass";
    lp.Q.value = 6;
    lp.frequency.setValueAtTime(Math.max(f * 1.2, 220), t);
    lp.frequency.exponentialRampToValueAtTime(Math.min(f * 7, 7500), t + 0.16);
    out.connect(lp);
    lp.connect(a.dest);
    const oscs = [-7, 7].map((cents) => {
      const o = ctx.createOscillator();
      o.type = "sawtooth";
      o.frequency.value = f;
      o.detune.value = cents;
      const og = ctx.createGain();
      og.gain.value = 0.24;
      o.connect(og);
      og.connect(out);
      o.start(t);
      return o;
    });
    const sub = ctx.createOscillator();
    sub.type = "square";
    sub.frequency.value = f / 2;
    const subG = ctx.createGain();
    subG.gain.value = 0.05;
    sub.connect(subG);
    subG.connect(out);
    sub.start(t);
    oscs.push(sub);
    out.gain.setValueAtTime(0.0001, t);
    out.gain.exponentialRampToValueAtTime(0.6, t + 0.01);
    return {
      gated: true,
      stop(pedal) {
        const s = a.now() + 0.01;
        out.gain.cancelScheduledValues(s);
        lp.frequency.cancelScheduledValues(s);
        out.gain.setTargetAtTime(0.0001, s, pedal ? 0.3 : 0.09);
        oscs.forEach((o) => o.stop(s + (pedal ? 1.3 : 0.6)));
      },
    };
  }

  /* ------------------------------------------------------------ rainbow ---
     One voice, and it has to forgive everything: a palm across eight keys
     has to sound like a chord and not like a crash. Soft attack, warm
     partials, a lowpass that keeps the top off. */

  function glow(a, m) {
    const f = FREQ(m);
    const { ctx, t } = a;
    const out = ctx.createGain();
    const lp = ctx.createBiquadFilter();
    lp.type = "lowpass";
    lp.frequency.setValueAtTime(Math.min(f * 6, 5200), t);
    lp.frequency.exponentialRampToValueAtTime(Math.max(f * 2, 700), t + 0.9);
    out.connect(lp);
    lp.connect(a.dest);

    const parts = [[1, 0.42, "triangle"], [1.002, 0.3, "triangle"], [2, 0.13, "sine"], [3, 0.05, "sine"]];
    const oscs = parts.map(([mult, g, type]) => {
      const o = ctx.createOscillator();
      o.type = type;
      o.frequency.value = f * mult;
      const og = ctx.createGain();
      og.gain.value = g;
      o.connect(og);
      og.connect(out);
      o.start(t);
      return o;
    });
    out.gain.setValueAtTime(0.0001, t);
    out.gain.exponentialRampToValueAtTime(0.62, t + 0.03);
    out.gain.setTargetAtTime(0.0001, t + 0.06, 0.85);
    return {
      gated: false,
      stop(pedal) {
        const s = a.now() + 0.01;
        out.gain.cancelScheduledValues(s);
        /* Generous even with the pedal up: a toddler's finger leaves a key
           long before the sound should end. */
        out.gain.setTargetAtTime(0.0001, s, pedal ? 0.5 : 0.28);
        oscs.forEach((o) => o.stop(s + (pedal ? 2 : 1.4)));
      },
    };
  }

  /* ----------------------------------------------------------- princess --- */

  /* A real toy piano is struck metal rods, not strings: bright, short, and
     deliberately out of tune with itself in the top partials. */
  function toypiano(a, m) {
    const f = FREQ(m);
    const { ctx, t } = a;
    const out = ctx.createGain();
    const hp = ctx.createBiquadFilter();
    hp.type = "highpass";
    hp.frequency.value = Math.min(f * 0.7, 900);
    out.connect(hp);
    hp.connect(a.dest);

    const parts = [[1, 0.4, "sine"], [2.02, 0.2, "sine"], [5.41, 0.12, "sine"], [8.93, 0.06, "sine"]];
    const oscs = parts.map(([mult, g, type]) => {
      const o = ctx.createOscillator();
      o.type = type;
      o.frequency.value = f * mult;
      const og = ctx.createGain();
      og.gain.value = g;
      /* The high rods die away first, which is what makes it a rod and not
         an organ pipe. */
      og.gain.setTargetAtTime(0.0001, t + 0.01, mult > 3 ? 0.09 : 0.5);
      o.connect(og);
      og.connect(out);
      o.start(t);
      return o;
    });
    const decay = Math.max(0.45, 1.7 - (m - 60) * 0.03);
    out.gain.setValueAtTime(0.0001, t);
    out.gain.exponentialRampToValueAtTime(0.85, t + 0.003);
    out.gain.setTargetAtTime(0.0001, t + 0.02, decay / 3);
    return {
      gated: false,
      stop(pedal) {
        const s = a.now() + 0.01;
        out.gain.cancelScheduledValues(s);
        out.gain.setTargetAtTime(0.0001, s, pedal ? 0.35 : 0.12);
        oscs.forEach((o) => o.stop(s + (pedal ? 1.2 : 0.6)));
      },
    };
  }

  /* A music-box comb: one clean sine, two inharmonic partials well above it,
     and a long tail. The little mechanical tick is a filtered noise blip. */
  function musicbox(a, m) {
    const f = FREQ(m);
    const { ctx, t } = a;
    const out = ctx.createGain();
    out.connect(a.dest);

    const parts = [[1, 0.5], [2.76, 0.14], [5.4, 0.06]];
    const oscs = parts.map(([mult, g]) => {
      const o = ctx.createOscillator();
      o.type = "sine";
      o.frequency.value = f * mult;
      const og = ctx.createGain();
      og.gain.value = g;
      og.gain.setTargetAtTime(0.0001, t + 0.01, mult > 2 ? 0.22 : 1.1);
      o.connect(og);
      og.connect(out);
      o.start(t);
      return o;
    });

    const tick = noise(a);
    const tickBp = ctx.createBiquadFilter();
    tickBp.type = "bandpass";
    tickBp.frequency.value = 3200;
    tickBp.Q.value = 1.2;
    const tickG = ctx.createGain();
    tickG.gain.setValueAtTime(0.09, t);
    tickG.gain.exponentialRampToValueAtTime(0.0001, t + 0.035);
    tick.connect(tickBp); tickBp.connect(tickG); tickG.connect(out);
    tick.start(t); tick.stop(t + 0.06);

    out.gain.setValueAtTime(0.0001, t);
    out.gain.exponentialRampToValueAtTime(0.8, t + 0.002);
    out.gain.setTargetAtTime(0.0001, t + 0.02, 0.95);
    return {
      gated: false,
      stop(pedal) {
        const s = a.now() + 0.01;
        out.gain.cancelScheduledValues(s);
        /* A music box has no damper. Lifting a finger does not stop it. */
        out.gain.setTargetAtTime(0.0001, s, pedal ? 0.9 : 0.55);
        oscs.forEach((o) => o.stop(s + (pedal ? 3 : 2.2)));
      },
    };
  }

  function harp(a, m) {
    const f = FREQ(m);
    const { ctx, t } = a;
    const out = ctx.createGain();
    const lp = ctx.createBiquadFilter();
    lp.type = "lowpass";
    lp.Q.value = 1.2;
    lp.frequency.setValueAtTime(Math.min(f * 9, 9000), t);
    lp.frequency.exponentialRampToValueAtTime(Math.max(f * 1.4, 400), t + 0.7);
    out.connect(lp);
    lp.connect(a.dest);

    const parts = [[1, 0.42, "triangle"], [2, 0.16, "triangle"], [3, 0.08, "sine"], [4.01, 0.04, "sine"]];
    const oscs = parts.map(([mult, g, type]) => {
      const o = ctx.createOscillator();
      o.type = type;
      o.frequency.value = f * mult;
      const og = ctx.createGain();
      og.gain.value = g;
      o.connect(og);
      og.connect(out);
      o.start(t);
      return o;
    });
    const decay = Math.max(0.8, 2.8 - (m - 60) * 0.04);
    out.gain.setValueAtTime(0.0001, t);
    out.gain.exponentialRampToValueAtTime(0.9, t + 0.006);
    out.gain.setTargetAtTime(0.0001, t + 0.03, decay / 3);
    return {
      gated: false,
      stop(pedal) {
        const s = a.now() + 0.01;
        out.gain.cancelScheduledValues(s);
        out.gain.setTargetAtTime(0.0001, s, pedal ? 0.6 : 0.3);
        oscs.forEach((o) => o.stop(s + (pedal ? 2 : 1.2)));
      },
    };
  }

  /* An FM bell: carrier and a modulator at a ratio that is not a whole
     number, so the partials land between the harmonics and it chimes. */
  function bells(a, m) {
    const f = FREQ(m);
    const { ctx, t } = a;
    const out = ctx.createGain();
    out.connect(a.dest);

    const carrier = ctx.createOscillator();
    carrier.type = "sine";
    carrier.frequency.value = f;
    const modOsc = ctx.createOscillator();
    modOsc.type = "sine";
    modOsc.frequency.value = f * 3.51;
    const mod = ctx.createGain();
    mod.gain.setValueAtTime(f * 4.5, t);
    mod.gain.exponentialRampToValueAtTime(f * 0.05, t + 1.6);
    modOsc.connect(mod);
    mod.connect(carrier.frequency);
    carrier.connect(out);
    carrier.start(t); modOsc.start(t);

    out.gain.setValueAtTime(0.0001, t);
    out.gain.exponentialRampToValueAtTime(0.6, t + 0.004);
    out.gain.setTargetAtTime(0.0001, t + 0.02, 1.3);
    return {
      gated: false,
      stop(pedal) {
        const s = a.now() + 0.01;
        out.gain.cancelScheduledValues(s);
        out.gain.setTargetAtTime(0.0001, s, pedal ? 1 : 0.6);
        carrier.stop(s + (pedal ? 3.5 : 2.4));
        modOsc.stop(s + (pedal ? 3.5 : 2.4));
      },
    };
  }

  /* ------------------------------------------------------------- studio --- */

  function strings(a, m) {
    const f = FREQ(m);
    const { ctx, t } = a;
    const out = ctx.createGain();
    const lp = ctx.createBiquadFilter();
    lp.type = "lowpass";
    lp.frequency.setValueAtTime(Math.max(f * 1.5, 350), t);
    lp.frequency.exponentialRampToValueAtTime(Math.min(f * 4.5, 6000), t + 0.4);
    out.connect(lp);
    lp.connect(a.dest);

    const oscs = [-9, 0, 9].map((cents) => {
      const o = ctx.createOscillator();
      o.type = "sawtooth";
      o.frequency.value = f;
      o.detune.value = cents;
      const og = ctx.createGain();
      og.gain.value = 0.16;
      o.connect(og);
      og.connect(out);
      o.start(t);
      return o;
    });
    /* A slow vibrato on the section, not on each player. */
    const lfo = ctx.createOscillator();
    lfo.type = "sine";
    lfo.frequency.value = 5.2;
    const lfoG = ctx.createGain();
    lfoG.gain.setValueAtTime(0, t);
    lfoG.gain.linearRampToValueAtTime(5, t + 0.9);
    lfo.connect(lfoG);
    oscs.forEach((o) => lfoG.connect(o.detune));
    lfo.start(t);
    oscs.push(lfo);

    out.gain.setValueAtTime(0.0001, t);
    out.gain.exponentialRampToValueAtTime(0.5, t + 0.22);
    return {
      gated: true,
      stop(pedal) {
        const s = a.now() + 0.01;
        out.gain.cancelScheduledValues(s);
        out.gain.setTargetAtTime(0.0001, s, pedal ? 0.4 : 0.18);
        oscs.forEach((o) => o.stop(s + (pedal ? 1.8 : 1)));
      },
    };
  }

  function brass(a, m) {
    const f = FREQ(m);
    const { ctx, t } = a;
    const out = ctx.createGain();
    const lp = ctx.createBiquadFilter();
    lp.type = "lowpass";
    lp.Q.value = 3;
    /* The brass "blip": the filter overshoots on the attack and settles. */
    lp.frequency.setValueAtTime(Math.max(f * 1.1, 260), t);
    lp.frequency.exponentialRampToValueAtTime(Math.min(f * 8, 8000), t + 0.09);
    lp.frequency.exponentialRampToValueAtTime(Math.min(f * 4, 5000), t + 0.35);
    out.connect(lp);
    lp.connect(a.dest);

    const oscs = [-4, 4].map((cents) => {
      const o = ctx.createOscillator();
      o.type = "sawtooth";
      o.frequency.value = f;
      o.detune.value = cents;
      const og = ctx.createGain();
      og.gain.value = 0.22;
      o.connect(og);
      og.connect(out);
      o.start(t);
      return o;
    });
    out.gain.setValueAtTime(0.0001, t);
    out.gain.exponentialRampToValueAtTime(0.62, t + 0.05);
    out.gain.setTargetAtTime(0.48, t + 0.06, 0.3);
    return {
      gated: true,
      stop(pedal) {
        const s = a.now() + 0.01;
        out.gain.cancelScheduledValues(s);
        lp.frequency.cancelScheduledValues(s);
        out.gain.setTargetAtTime(0.0001, s, pedal ? 0.25 : 0.08);
        oscs.forEach((o) => o.stop(s + (pedal ? 1.2 : 0.5)));
      },
    };
  }

  function bass(a, m) {
    const f = FREQ(m);
    const { ctx, t } = a;
    const out = ctx.createGain();
    const lp = ctx.createBiquadFilter();
    lp.type = "lowpass";
    lp.Q.value = 7;
    lp.frequency.setValueAtTime(Math.min(f * 9, 2600), t);
    lp.frequency.exponentialRampToValueAtTime(Math.max(f * 1.6, 90), t + 0.22);
    out.connect(lp);
    lp.connect(a.dest);

    const o1 = ctx.createOscillator();
    o1.type = "square";
    o1.frequency.value = f;
    const g1 = ctx.createGain();
    g1.gain.value = 0.2;
    o1.connect(g1); g1.connect(out); o1.start(t);

    const sub = ctx.createOscillator();
    sub.type = "sine";
    sub.frequency.value = f / 2;
    const g2 = ctx.createGain();
    g2.gain.value = 0.38;
    sub.connect(g2); g2.connect(out); sub.start(t);

    out.gain.setValueAtTime(0.0001, t);
    out.gain.exponentialRampToValueAtTime(0.75, t + 0.008);
    out.gain.setTargetAtTime(0.5, t + 0.02, 0.25);
    return {
      gated: true,
      stop(pedal) {
        const s = a.now() + 0.01;
        out.gain.cancelScheduledValues(s);
        lp.frequency.cancelScheduledValues(s);
        out.gain.setTargetAtTime(0.0001, s, pedal ? 0.2 : 0.06);
        [o1, sub].forEach((o) => o.stop(s + (pedal ? 1 : 0.4)));
      },
    };
  }

  /* --------------------------------------------------------------- drums ---
     One shot each. They schedule their own end, so there is no handle to
     hold and nothing to release. */

  function drumKick(a) {
    const { ctx, t } = a;
    const o = ctx.createOscillator();
    o.type = "sine";
    o.frequency.setValueAtTime(150, t);
    o.frequency.exponentialRampToValueAtTime(45, t + 0.09);
    const g = ctx.createGain();
    g.gain.setValueAtTime(0.0001, t);
    g.gain.exponentialRampToValueAtTime(0.9, t + 0.005);
    g.gain.exponentialRampToValueAtTime(0.0001, t + 0.36);
    o.connect(g); g.connect(a.dest);
    o.start(t); o.stop(t + 0.4);
  }

  function drumSnare(a) {
    const { ctx, t } = a;
    const n = noise(a);
    const hp = ctx.createBiquadFilter();
    hp.type = "highpass";
    hp.frequency.value = 1100;
    const ng = ctx.createGain();
    ng.gain.setValueAtTime(0.5, t);
    ng.gain.exponentialRampToValueAtTime(0.0001, t + 0.19);
    n.connect(hp); hp.connect(ng); ng.connect(a.dest);
    n.start(t); n.stop(t + 0.24);

    const o = ctx.createOscillator();
    o.type = "triangle";
    o.frequency.setValueAtTime(196, t);
    o.frequency.exponentialRampToValueAtTime(150, t + 0.1);
    const g = ctx.createGain();
    g.gain.setValueAtTime(0.3, t);
    g.gain.exponentialRampToValueAtTime(0.0001, t + 0.13);
    o.connect(g); g.connect(a.dest);
    o.start(t); o.stop(t + 0.16);
  }

  function drumHat(a) {
    const { ctx, t } = a;
    const n = noise(a);
    const hp = ctx.createBiquadFilter();
    hp.type = "highpass";
    hp.frequency.value = 7400;
    const g = ctx.createGain();
    g.gain.setValueAtTime(0.34, t);
    g.gain.exponentialRampToValueAtTime(0.0001, t + 0.055);
    n.connect(hp); hp.connect(g); g.connect(a.dest);
    n.start(t); n.stop(t + 0.08);
  }

  function drumClap(a) {
    const { ctx, t } = a;
    /* Three bursts a few milliseconds apart is what makes hands and not a
       single slap. */
    [0, 0.011, 0.023].forEach((off, i) => {
      const n = noise(a);
      const bp = ctx.createBiquadFilter();
      bp.type = "bandpass";
      bp.frequency.value = 1150;
      bp.Q.value = 1.4;
      const g = ctx.createGain();
      g.gain.setValueAtTime(i === 2 ? 0.42 : 0.26, t + off);
      g.gain.exponentialRampToValueAtTime(0.0001, t + off + (i === 2 ? 0.16 : 0.05));
      n.connect(bp); bp.connect(g); g.connect(a.dest);
      n.start(t + off); n.stop(t + off + 0.2);
    });
  }

  function drumTom(a) {
    const { ctx, t } = a;
    const o = ctx.createOscillator();
    o.type = "sine";
    o.frequency.setValueAtTime(230, t);
    o.frequency.exponentialRampToValueAtTime(110, t + 0.22);
    const g = ctx.createGain();
    g.gain.setValueAtTime(0.0001, t);
    g.gain.exponentialRampToValueAtTime(0.6, t + 0.006);
    g.gain.exponentialRampToValueAtTime(0.0001, t + 0.34);
    o.connect(g); g.connect(a.dest);
    o.start(t); o.stop(t + 0.38);
  }

  function drumBell(a) {
    const { ctx, t } = a;
    const bp = ctx.createBiquadFilter();
    bp.type = "bandpass";
    bp.frequency.value = 2640;
    bp.Q.value = 2.2;
    const g = ctx.createGain();
    g.gain.setValueAtTime(0.3, t);
    g.gain.exponentialRampToValueAtTime(0.0001, t + 0.3);
    bp.connect(g); g.connect(a.dest);
    [540, 800].forEach((hz) => {
      const o = ctx.createOscillator();
      o.type = "square";
      o.frequency.value = hz;
      o.connect(bp);
      o.start(t); o.stop(t + 0.34);
    });
  }

  /* The metronome. Two pitches so the first beat of the bar is findable
     without counting. It is not a drum pad and never appears as one. */
  function metroClick(a, hz, level) {
    const { ctx, t } = a;
    const o = ctx.createOscillator();
    o.type = "square";
    o.frequency.value = hz;
    const bp = ctx.createBiquadFilter();
    bp.type = "bandpass";
    bp.frequency.value = hz;
    bp.Q.value = 4;
    const g = ctx.createGain();
    g.gain.setValueAtTime(level, t);
    g.gain.exponentialRampToValueAtTime(0.0001, t + 0.04);
    o.connect(bp); bp.connect(g); g.connect(a.dest);
    o.start(t); o.stop(t + 0.06);
  }

  /* ------------------------------------------------------------ registry --- */

  KB.voices = {
    piano: { name: "Piano", make: piano },
    epiano: { name: "E. Piano", make: epiano },
    organ: { name: "Organ", make: organ },
    synth: { name: "Synth", make: synth },
    glow: { name: "Glow", make: glow },
    toypiano: { name: "Piano", make: toypiano },
    musicbox: { name: "Music Box", make: musicbox },
    harp: { name: "Harp", make: harp },
    bells: { name: "Bells", make: bells },
    strings: { name: "Strings", make: strings },
    brass: { name: "Brass", make: brass },
    bass: { name: "Bass", make: bass },
  };

  KB.drums = {
    kick: { name: "Kick", make: drumKick },
    snare: { name: "Snare", make: drumSnare },
    hat: { name: "Hat", make: drumHat },
    clap: { name: "Clap", make: drumClap },
    tom: { name: "Tom", make: drumTom },
    bell: { name: "Bell", make: drumBell },
    /* Metronome only — deliberately not on any drum pad. */
    tick: { name: "Tick", make: (a) => metroClick(a, 1400, 0.16) },
    tock: { name: "Tock", make: (a) => metroClick(a, 2100, 0.24) },
  };

  KB.freq = FREQ;
})();
