// Hand-written Map Bridge voice player, matching learnmore.js's split from its
// generated clip-text module: mapbridge-clips.js is regenerated by
// tools/build-mapbridge-manifest.py and must stay data-only, or a future
// regeneration silently deletes this player.
let engine = null;
let current = null;

export function configureMapBridge(options = {}) {
  engine = options.engine ?? null;
}

export function stopMapBridgeClip() {
  if (current) {
    current.pause();
    current.currentTime = 0;
    current = null;
  }
  if (engine) engine.duck('voice', false);
}

export function speakMapBridgeClip(clipId) {
  stopMapBridgeClip();
  if (!clipId || typeof Audio === 'undefined') return false;
  const audio = new Audio(`audio/mapbridge/${clipId}.m4a`);
  current = audio;
  if (engine) {
    engine.connectVoice(audio);
    engine.duck('voice', true);
  }
  const release = () => {
    if (current === audio) current = null;
    if (engine) engine.duck('voice', false);
  };
  audio.addEventListener('ended', release, { once: true });
  audio.addEventListener('error', release, { once: true });
  audio.play().catch(release);
  return true;
}
