import {FIVE_SUMS_TITLE,FIVE_SUMS_MODES,makeBag,draw,emptyBoard,validateMove,applyMove,formedLines,arithmetic,hintFor,findMove,key} from '../engine/five-sums.js';
const q=new URLSearchParams(location.search),theme=q.get('theme')==='garden'?'garden':'space';
const state={theme,mode:'make5',help:'learn',board:emptyBoard(),bag:makeBag(Number(q.get('seed'))||20260929),rack:[],pending:[],selected:null,misses:0,score:0,message:'Place tiles to make 5.',celebration:''};
const VOICE={start:'Place number tiles in one line. Make the target sum.',hint:'Add the numbers in your line. What number do you still need?',reveal:'Try the glowing square and tile.',win:'Great sum!'};
function sfx(kind){const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const a=sfx.a||(sfx.a=new A),o=a.createOscillator(),g=a.createGain(),now=a.currentTime;o.type=kind==='wrong'?'sawtooth':'sine';o.frequency.setValueAtTime(kind==='wrong'?180:kind==='tap'?360:620,now);if(kind==='win')o.frequency.exponentialRampToValueAtTime(1100,now+.28);g.gain.setValueAtTime(.12,now);g.gain.exponentialRampToValueAtTime(.001,now+.3);o.connect(g).connect(a.destination);o.start();o.stop(now+.31);}
function deal(){const d=draw(state.bag,5);state.rack=d.tiles;state.bag=d.bag.length<15?d.bag.concat(makeBag(state.score+17)):d.bag;state.pending=[];state.selected=null;state.misses=0;state.message='Place tiles to '+targetText()+'.';render();}
function targetText(){const m=FIVE_SUMS_MODES[state.mode];return m.targets?'make '+m.targets.join(', '):'make a multiple of 5';}
function currentArithmetic(){if(!state.pending.length)return '';const lines=formedLines(state.board,state.pending);if(lines.length)return lines.map(arithmetic).join('  •  ');return state.pending.map(p=>p.value).join(' + ')+' = '+state.pending.reduce((n,p)=>n+p.value,0);}
function place(index,r,c){if(index==null||state.rack[index]==null||state.pending.some(p=>p.r===r&&p.c===c)||state.board.cells[key(r,c)]!=null){sfx('wrong');state.message='Choose a free tile and an empty square.';render();return;}state.pending.push({r,c,value:state.rack[index],rackIndex:index});state.selected=null;sfx('tap');state.message=state.help==='learn'?currentArithmetic()+' — '+targetText()+'.':currentArithmetic();render();}
function submit(){const v=validateMove(state.board,state.pending,state.mode);if(!v.ok){state.misses++;state.message=v.message;const h=hintFor(state.misses,findMove(state.board,state.rack,state.mode));if(h){state.message+=' '+h.text;if(h.level===3)state.reveal=h.placements;}sfx('wrong');render();return;}state.board=applyMove(state.board,state.pending);state.score+=v.score;state.pending.forEach(p=>state.rack[p.rackIndex]=null);state.message=v.lines.map(arithmetic).join('  •  ');state.celebration=v.celebration;sfx('win');render();setTimeout(()=>{state.celebration='';if(state.rack.filter(Boolean).length<2)deal();else render();},900);}
function replay(){sfx('tap');const bubble=state.misses>=3?VOICE.reveal:state.misses>=2?VOICE.hint:VOICE.start;state.message=bubble+' '+(currentArithmetic()||'');render();}
const CORNER_ART={space:'assets/space/icons/rainbow-star.png',garden:'assets/unicorn/icons/flower-pink.png'};
const CELEBRATION_ART={
  space:{double:['assets/space/icons/sparkle-blue.png','assets/space/icons/sparkle-purple.png'],grand:['assets/space/icons/glowstar-gold.png','assets/space/icons/glowstar-purple.png','assets/space/icons/trophy.png'],line:['assets/space/icons/sparkle-green.png']},
  garden:{double:['assets/unicorn/icons/flower-blue.png','assets/unicorn/icons/flower-coral.png'],grand:['assets/unicorn/icons/bouquet.png','assets/unicorn/icons/rainbow.png','assets/unicorn/icons/flower-purple.png'],line:['assets/unicorn/icons/sparkle.png']}
};
function spritesRow(theme,celebration){const art=CELEBRATION_ART[theme][celebration]||[];return art.length?`<div class="sprites-row">${art.map(src=>`<img src="${src}" alt="" aria-hidden="true">`).join('')}</div>`:'';}
function render(){const mode=FIVE_SUMS_MODES[state.mode],h=[];for(let r=0;r<7;r++)for(let c=0;c<7;c++){const fixed=state.board.cells[key(r,c)],p=state.pending.find(x=>x.r===r&&x.c===c),rev=state.reveal&&state.reveal.some(x=>x.r===r&&x.c===c);h.push(`<button class="cell ${r===3&&c===3?'center ':''}${p?'pending ':''}${rev?'reveal':''}" data-r="${r}" data-c="${c}" aria-label="row ${r+1}, column ${c+1}${fixed!=null?', '+fixed:''}">${p?p.value:fixed??''}</button>`);}const tiles=state.rack.map((n,i)=>`<button class="tile ${state.selected===i?'selected ':''}${n==null?'used':''}" data-tile="${i}" draggable="${n!=null}" aria-label="number ${n??'used'}">${n??''}</button>`).join('');const corner=CORNER_ART[state.theme];document.querySelector('#app').innerHTML=`<section class="game ${state.theme}"><header class="top"><a class="round" href="${state.theme==='space'?'space-math.html':'unicorn-math.html'}" aria-label="Back">‹</a><h1 class="title">${FIVE_SUMS_TITLE}</h1><button class="round speaker" id="speaker" aria-label="Hear the instruction">🔊</button></header><nav class="controls" aria-label="Game choices">${Object.values(FIVE_SUMS_MODES).map(m=>`<button data-mode="${m.id}" aria-pressed="${m.id===state.mode}">${m.label}</button>`).join('')}${['learn','normal','challenge'].map(x=>`<button data-help="${x}" aria-pressed="${x===state.help}">${x[0].toUpperCase()+x.slice(1)}</button>`).join('')}</nav><div class="status"><span>${state.message}</span><strong class="equation">${currentArithmetic()}</strong></div><div class="play"><div class="board-wrap"><div class="backdrop"></div><img class="corner tl" src="${corner}" alt="" aria-hidden="true"><img class="corner tr" src="${corner}" alt="" aria-hidden="true"><img class="corner bl" src="${corner}" alt="" aria-hidden="true"><img class="corner br" src="${corner}" alt="" aria-hidden="true"><div class="board">${h.join('')}</div></div><aside class="side"><div class="target">${mode.label}<br>Score ${state.score}</div><div class="rack">${tiles}</div><div class="actions"><button class="clear" id="clear">Try again</button><button class="submit" id="submit">Play line</button></div></aside></div>${state.celebration?`<div class="celebrate"><span>${state.celebration==='double'?(state.theme==='space'?'Double Orbit!':'Double Bloom!'):state.celebration==='grand'?'Super Star Sums!':'Great sum!'}</span>${spritesRow(state.theme,state.celebration)}</div>`:''}</section>`;bind();window.__fiveSums={state,place,submit,render,validateMove};}
function bind(){document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{sfx('tap');state.mode=b.dataset.mode;state.board=emptyBoard();deal();});document.querySelectorAll('[data-help]').forEach(b=>b.onclick=()=>{sfx('tap');state.help=b.dataset.help;state.message=b.textContent+' help is on.';render();});document.querySelectorAll('[data-tile]').forEach(b=>{b.onclick=()=>{if(state.rack[+b.dataset.tile]==null)return sfx('wrong');sfx('tap');state.selected=+b.dataset.tile;render();};b.ondragstart=e=>e.dataTransfer.setData('text/plain',b.dataset.tile);});document.querySelectorAll('.cell').forEach(b=>{b.onclick=()=>place(state.selected,+b.dataset.r,+b.dataset.c);b.ondragover=e=>e.preventDefault();b.ondrop=e=>{e.preventDefault();place(+e.dataTransfer.getData('text/plain'),+b.dataset.r,+b.dataset.c);};});document.querySelector('#submit').onclick=submit;document.querySelector('#clear').onclick=()=>{sfx('tap');state.pending=[];state.reveal=null;state.message='Choose another place.';render();};document.querySelector('#speaker').onclick=replay;}
deal();
