// Generated by music-book/tools/stage-title-this-fix-testhub.sh. Do not edit.
window.LISTEN_CLIPS = [
{
"id": "ode-to-joy",
"file": "ode-to-joy.m4a",
"class": "classical",
"sentence": "This music is called Ode to Joy.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "fur-elise",
"file": "fur-elise.m4a",
"class": "classical",
"sentence": "This music is called Für Elise.",
"beforePeakGapDb": -7.1,
"afterPeakGapDb": -2.33,
"openingBoostDb": 5.27,
"ab": true
},
{
"id": "moonlight-sonata",
"file": "moonlight-sonata.m4a",
"class": "classical",
"sentence": "This music is called Moonlight Sonata.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "symphony-5-opening",
"file": "symphony-5-opening.m4a",
"class": "classical",
"sentence": "This music is called Symphony Number Five, the opening.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "twinkle",
"file": "twinkle.m4a",
"class": "song",
"sentence": "This song is called Twinkle Twinkle Little Star.",
"openingBoostDb": 2.37,
"ab": false
},
{
"id": "swan-lake-theme",
"file": "swan-lake-theme.m4a",
"class": "classical",
"sentence": "This music is called Swan Lake, the theme.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "mary-had-little-lamb",
"file": "mary-had-little-lamb.m4a",
"class": "song",
"sentence": "This song is called Mary Had a Little Lamb.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "frere-jacques",
"file": "frere-jacques.m4a",
"class": "song",
"sentence": "This song is called Frère Jacques.",
"beforePeakGapDb": -6.03,
"afterPeakGapDb": -1.45,
"openingBoostDb": 4.49,
"ab": true
},
{
"id": "row-row-row-your-boat",
"file": "row-row-row-your-boat.m4a",
"class": "song",
"sentence": "This song is called Row, Row, Row Your Boat.",
"openingBoostDb": 3.33,
"ab": false
},
{
"id": "old-macdonald",
"file": "old-macdonald.m4a",
"class": "song",
"sentence": "This song is called Old MacDonald Had a Farm.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "bingo",
"file": "bingo.m4a",
"class": "song",
"sentence": "This song is called BINGO.",
"openingBoostDb": 1.61,
"ab": false
},
{
"id": "london-bridge",
"file": "london-bridge.m4a",
"class": "song",
"sentence": "This song is called London Bridge Is Falling Down.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "pop-goes-weasel",
"file": "pop-goes-weasel.m4a",
"class": "song",
"sentence": "This song is called Pop Goes the Weasel.",
"openingBoostDb": 2.96,
"ab": false
},
{
"id": "three-blind-mice",
"file": "three-blind-mice.m4a",
"class": "song",
"sentence": "This song is called Three Blind Mice.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "hot-cross-buns",
"file": "hot-cross-buns.m4a",
"class": "song",
"sentence": "This song is called Hot Cross Buns.",
"openingBoostDb": 0.65,
"ab": false
},
{
"id": "this-old-man",
"file": "this-old-man.m4a",
"class": "song",
"sentence": "This song is called This Old Man.",
"openingBoostDb": 2.7,
"ab": false
},
{
"id": "farmer-in-dell",
"file": "farmer-in-dell.m4a",
"class": "song",
"sentence": "This song is called The Farmer in the Dell.",
"openingBoostDb": 3.75,
"ab": false
},
{
"id": "mulberry-bush",
"file": "mulberry-bush.m4a",
"class": "song",
"sentence": "This song is called Here We Go Round the Mulberry Bush.",
"openingBoostDb": 0.54,
"ab": false
},
{
"id": "rock-a-bye-baby",
"file": "rock-a-bye-baby.m4a",
"class": "song",
"sentence": "This song is called Rock-a-bye Baby.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "skip-to-my-lou",
"file": "skip-to-my-lou.m4a",
"class": "song",
"sentence": "This song is called Skip to My Lou.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "amazing-grace-new-britain",
"file": "amazing-grace-new-britain.m4a",
"class": "song",
"sentence": "This song is called Amazing Grace.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "when-saints-go-marching",
"file": "when-saints-go-marching.m4a",
"class": "song",
"sentence": "This song is called When the Saints Go Marching In.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "simple-gifts",
"file": "simple-gifts.m4a",
"class": "song",
"sentence": "This song is called Simple Gifts.",
"openingBoostDb": 3.62,
"ab": false
},
{
"id": "my-bonnie",
"file": "my-bonnie.m4a",
"class": "song",
"sentence": "This song is called My Bonnie Lies over the Ocean.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "home-on-range",
"file": "home-on-range.m4a",
"class": "song",
"sentence": "This song is called Home on the Range.",
"beforePeakGapDb": -8.12,
"afterPeakGapDb": -2.75,
"openingBoostDb": 5.36,
"ab": true
},
{
"id": "happy-birthday",
"file": "happy-birthday.m4a",
"class": "song",
"sentence": "This song is called Happy Birthday to You.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "jolly-good-fellow",
"file": "jolly-good-fellow.m4a",
"class": "song",
"sentence": "This song is called For He's a Jolly Good Fellow.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "jingle-bells",
"file": "jingle-bells.m4a",
"class": "song",
"sentence": "This song is called Jingle Bells.",
"openingBoostDb": 1.98,
"ab": false
},
{
"id": "silent-night",
"file": "silent-night.m4a",
"class": "song",
"sentence": "This song is called Silent Night.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "o-tannenbaum",
"file": "o-tannenbaum.m4a",
"class": "song",
"sentence": "This song is called O Tannenbaum.",
"openingBoostDb": 2.61,
"ab": false
},
{
"id": "deck-the-hall",
"file": "deck-the-hall.m4a",
"class": "song",
"sentence": "This song is called Deck the Hall.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "we-wish-merry-christmas",
"file": "we-wish-merry-christmas.m4a",
"class": "song",
"sentence": "This song is called We Wish You a Merry Christmas.",
"beforePeakGapDb": -6.49,
"afterPeakGapDb": -2.0,
"openingBoostDb": 4.37,
"ab": true
},
{
"id": "first-noel",
"file": "first-noel.m4a",
"class": "song",
"sentence": "This song is called The First Noel.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "joy-to-world",
"file": "joy-to-world.m4a",
"class": "song",
"sentence": "This song is called Joy to the World.",
"openingBoostDb": 2.4,
"ab": false
},
{
"id": "auld-lang-syne",
"file": "auld-lang-syne.m4a",
"class": "song",
"sentence": "This song is called Auld Lang Syne.",
"openingBoostDb": 1.56,
"ab": false
},
{
"id": "sakura-sakura",
"file": "sakura-sakura.m4a",
"class": "song",
"sentence": "This song is called Sakura Sakura.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "arirang",
"file": "arirang.m4a",
"class": "song",
"sentence": "This song is called Arirang.",
"openingBoostDb": 0.15,
"ab": false
},
{
"id": "mo-li-hua",
"file": "mo-li-hua.m4a",
"class": "song",
"sentence": "This song is called Mo Li Hua.",
"openingBoostDb": 1.03,
"ab": false
},
{
"id": "rasa-sayang",
"file": "rasa-sayang.m4a",
"class": "song",
"sentence": "This song is called Rasa Sayang.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "burung-kakak-tua",
"file": "burung-kakak-tua.m4a",
"class": "song",
"sentence": "This song is called Burung Kakak Tua.",
"openingBoostDb": 0.38,
"ab": false
},
{
"id": "leron-leron-sinta",
"file": "leron-leron-sinta.m4a",
"class": "song",
"sentence": "This song is called Leron, Leron Sinta.",
"openingBoostDb": 2.72,
"ab": false
},
{
"id": "lao-duang-duen",
"file": "lao-duang-duen.m4a",
"class": "song",
"sentence": "This song is called Lao Duang Duen.",
"openingBoostDb": 2.68,
"ab": false
},
{
"id": "raghupati-raghava",
"file": "raghupati-raghava.m4a",
"class": "song",
"sentence": "This song is called Raghupati Raghava Raja Ram.",
"openingBoostDb": 1.27,
"ab": false
},
{
"id": "uskudara-gider-iken",
"file": "uskudara-gider-iken.m4a",
"class": "song",
"sentence": "This song is called Üsküdar'a Gider İken.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "hava-nagila",
"file": "hava-nagila.m4a",
"class": "song",
"sentence": "This song is called Hava Nagila.",
"openingBoostDb": 0.09,
"ab": false
},
{
"id": "kalinka",
"file": "kalinka.m4a",
"class": "song",
"sentence": "This song is called Kalinka.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "shchedryk",
"file": "shchedryk.m4a",
"class": "song",
"sentence": "This song is called Shchedryk.",
"openingBoostDb": 2.36,
"ab": false
},
{
"id": "nkosi-sikelel-iafrika",
"file": "nkosi-sikelel-iafrika.m4a",
"class": "song",
"sentence": "This song is called Nkosi Sikelel' iAfrika.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "misirlou",
"file": "misirlou.m4a",
"class": "song",
"sentence": "This song is called Misirlou.",
"openingBoostDb": 1.92,
"ab": false
},
{
"id": "waltzing-matilda",
"file": "waltzing-matilda.m4a",
"class": "song",
"sentence": "This song is called Waltzing Matilda.",
"openingBoostDb": 0.17,
"ab": false
},
{
"id": "el-condor-pasa",
"file": "el-condor-pasa.m4a",
"class": "song",
"sentence": "This song is called El Cóndor Pasa.",
"openingBoostDb": 0.97,
"ab": false
},
{
"id": "la-bamba",
"file": "la-bamba.m4a",
"class": "song",
"sentence": "This song is called La Bamba.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "greensleeves",
"file": "greensleeves.m4a",
"class": "song",
"sentence": "This song is called Greensleeves.",
"openingBoostDb": 2.49,
"ab": false
},
{
"id": "bach-prelude-c-major-bwv-846",
"file": "bach-prelude-c-major-bwv-846.m4a",
"class": "classical",
"sentence": "This music is called Prelude in C major, BWV 846.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "bach-air-orchestral-suite-3",
"file": "bach-air-orchestral-suite-3.m4a",
"class": "classical",
"sentence": "This music is called Air from Orchestral Suite No. 3.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "bach-jesu-joy",
"file": "bach-jesu-joy.m4a",
"class": "classical",
"sentence": "This music is called Jesu, Joy of Man's Desiring.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "bach-cello-suite-1-prelude",
"file": "bach-cello-suite-1-prelude.m4a",
"class": "classical",
"sentence": "This music is called Cello Suite No. 1 — Prelude.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "vivaldi-spring-1",
"file": "vivaldi-spring-1.m4a",
"class": "classical",
"sentence": "This music is called The Four Seasons — Spring.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "vivaldi-summer-storm",
"file": "vivaldi-summer-storm.m4a",
"class": "classical",
"sentence": "This music is called The Four Seasons — Summer Storm.",
"openingBoostDb": 1.96,
"ab": false
},
{
"id": "vivaldi-winter-1",
"file": "vivaldi-winter-1.m4a",
"class": "classical",
"sentence": "This music is called The Four Seasons — Winter.",
"openingBoostDb": 0.28,
"ab": false
},
{
"id": "handel-hallelujah-chorus",
"file": "handel-hallelujah-chorus.m4a",
"class": "classical",
"sentence": "This music is called Messiah — Hallelujah Chorus.",
"openingBoostDb": 0.98,
"ab": false
},
{
"id": "handel-water-music-hornpipe",
"file": "handel-water-music-hornpipe.m4a",
"class": "classical",
"sentence": "This music is called Water Music — Hornpipe.",
"openingBoostDb": 3.86,
"ab": false
},
{
"id": "handel-royal-fireworks-rejouissance",
"file": "handel-royal-fireworks-rejouissance.m4a",
"class": "classical",
"sentence": "This music is called Music for the Royal Fireworks — La Réjouissance.",
"openingBoostDb": 0.62,
"ab": false
},
{
"id": "pachelbel-canon-d",
"file": "pachelbel-canon-d.m4a",
"class": "classical",
"sentence": "This music is called Canon in D.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "haydn-surprise-symphony-94-2",
"file": "haydn-surprise-symphony-94-2.m4a",
"class": "classical",
"sentence": "This music is called Symphony No. 94 — Surprise.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "haydn-trumpet-concerto-3",
"file": "haydn-trumpet-concerto-3.m4a",
"class": "classical",
"sentence": "This music is called Trumpet Concerto — third movement.",
"openingBoostDb": 2.17,
"ab": false
},
{
"id": "mozart-eine-kleine-nachtmusik-1",
"file": "mozart-eine-kleine-nachtmusik-1.m4a",
"class": "classical",
"sentence": "This music is called Eine kleine Nachtmusik.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "mozart-rondo-alla-turca",
"file": "mozart-rondo-alla-turca.m4a",
"class": "classical",
"sentence": "This music is called Rondo alla Turca.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "mozart-symphony-40-1",
"file": "mozart-symphony-40-1.m4a",
"class": "classical",
"sentence": "This music is called Symphony No. 40.",
"openingBoostDb": 0.22,
"ab": false
},
{
"id": "mozart-piano-sonata-k545-1",
"file": "mozart-piano-sonata-k545-1.m4a",
"class": "classical",
"sentence": "This music is called Piano Sonata in C, K.545.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "mozart-ah-vous-dirai-je-variations",
"file": "mozart-ah-vous-dirai-je-variations.m4a",
"class": "classical",
"sentence": "This music is called Twelve Variations on 'Ah! vous dirai-je, maman'.",
"openingBoostDb": 0.68,
"ab": false
},
{
"id": "beethoven-symphony-7-2",
"file": "beethoven-symphony-7-2.m4a",
"class": "classical",
"sentence": "This music is called Symphony No. 7 — second movement.",
"openingBoostDb": 0.43,
"ab": false
},
{
"id": "schubert-ave-maria",
"file": "schubert-ave-maria.m4a",
"class": "classical",
"sentence": "This music is called Ave Maria.",
"openingBoostDb": 0.11,
"ab": false
},
{
"id": "schubert-die-forelle",
"file": "schubert-die-forelle.m4a",
"class": "classical",
"sentence": "This music is called The Trout.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "mendelssohn-wedding-march",
"file": "mendelssohn-wedding-march.m4a",
"class": "classical",
"sentence": "This music is called Wedding March.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "mendelssohn-spring-song",
"file": "mendelssohn-spring-song.m4a",
"class": "classical",
"sentence": "This music is called Spring Song.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "mendelssohn-violin-concerto-opening",
"file": "mendelssohn-violin-concerto-opening.m4a",
"class": "classical",
"sentence": "This music is called Violin Concerto — opening.",
"openingBoostDb": 0.66,
"ab": false
},
{
"id": "chopin-nocturne-op9-no2",
"file": "chopin-nocturne-op9-no2.m4a",
"class": "classical",
"sentence": "This music is called Nocturne in E-flat, Opus Nine Number Two.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "chopin-minute-waltz",
"file": "chopin-minute-waltz.m4a",
"class": "classical",
"sentence": "This music is called Minute Waltz.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "chopin-raindrop-prelude",
"file": "chopin-raindrop-prelude.m4a",
"class": "classical",
"sentence": "This music is called Raindrop Prelude.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "chopin-fantaisie-impromptu",
"file": "chopin-fantaisie-impromptu.m4a",
"class": "classical",
"sentence": "This music is called Fantaisie-Impromptu.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "schumann-traumerei",
"file": "schumann-traumerei.m4a",
"class": "classical",
"sentence": "This music is called Träumerei.",
"beforePeakGapDb": -7.64,
"afterPeakGapDb": -2.45,
"openingBoostDb": 5.3,
"ab": true
},
{
"id": "schumann-happy-farmer",
"file": "schumann-happy-farmer.m4a",
"class": "classical",
"sentence": "This music is called The Happy Farmer.",
"openingBoostDb": 0.38,
"ab": false
},
{
"id": "schumann-foreign-lands-people",
"file": "schumann-foreign-lands-people.m4a",
"class": "classical",
"sentence": "This music is called Of Foreign Lands and People.",
"openingBoostDb": 0.32,
"ab": false
},
{
"id": "brahms-lullaby",
"file": "brahms-lullaby.m4a",
"class": "classical",
"sentence": "This music is called Brahms's Lullaby.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "brahms-hungarian-dance-5",
"file": "brahms-hungarian-dance-5.m4a",
"class": "classical",
"sentence": "This music is called Hungarian Dance No. 5.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "brahms-waltz-op39-no15",
"file": "brahms-waltz-op39-no15.m4a",
"class": "classical",
"sentence": "This music is called Waltz in A-flat, Opus Thirty-Nine Number Fifteen.",
"openingBoostDb": 1.77,
"ab": false
},
{
"id": "tchaikovsky-sugar-plum-fairy",
"file": "tchaikovsky-sugar-plum-fairy.m4a",
"class": "classical",
"sentence": "This music is called Dance of the Sugar Plum Fairy.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "tchaikovsky-waltz-flowers",
"file": "tchaikovsky-waltz-flowers.m4a",
"class": "classical",
"sentence": "This music is called Waltz of the Flowers.",
"openingBoostDb": 1.55,
"ab": false
},
{
"id": "tchaikovsky-nutcracker-march",
"file": "tchaikovsky-nutcracker-march.m4a",
"class": "classical",
"sentence": "This music is called The Nutcracker — March.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "tchaikovsky-trepak",
"file": "tchaikovsky-trepak.m4a",
"class": "classical",
"sentence": "This music is called Russian Dance (Trepak).",
"beforePeakGapDb": -5.75,
"afterPeakGapDb": -1.54,
"openingBoostDb": 3.98,
"ab": true
},
{
"id": "tchaikovsky-piano-concerto-1-opening",
"file": "tchaikovsky-piano-concerto-1-opening.m4a",
"class": "classical",
"sentence": "This music is called Piano Concerto No. 1 — opening.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "saint-saens-the-swan",
"file": "saint-saens-the-swan.m4a",
"class": "classical",
"sentence": "This music is called The Swan.",
"openingBoostDb": 1.78,
"ab": false
},
{
"id": "saint-saens-aquarium",
"file": "saint-saens-aquarium.m4a",
"class": "classical",
"sentence": "This music is called Aquarium.",
"openingBoostDb": 1.69,
"ab": false
},
{
"id": "saint-saens-danse-macabre",
"file": "saint-saens-danse-macabre.m4a",
"class": "classical",
"sentence": "This music is called Danse macabre.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "grieg-morning-mood",
"file": "grieg-morning-mood.m4a",
"class": "classical",
"sentence": "This music is called Morning Mood.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "grieg-mountain-king",
"file": "grieg-mountain-king.m4a",
"class": "classical",
"sentence": "This music is called In the Hall of the Mountain King.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "grieg-anitras-dance",
"file": "grieg-anitras-dance.m4a",
"class": "classical",
"sentence": "This music is called Anitra's Dance.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "dvorak-new-world-largo",
"file": "dvorak-new-world-largo.m4a",
"class": "classical",
"sentence": "This music is called Symphony No. 9 — Largo.",
"openingBoostDb": 0.5,
"ab": false
},
{
"id": "dvorak-humoresque-7",
"file": "dvorak-humoresque-7.m4a",
"class": "classical",
"sentence": "This music is called Humoresque No. 7.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "dvorak-slavonic-dance-8",
"file": "dvorak-slavonic-dance-8.m4a",
"class": "classical",
"sentence": "This music is called Slavonic Dance No. 8.",
"openingBoostDb": 0.01,
"ab": false
},
{
"id": "mussorgsky-promenade",
"file": "mussorgsky-promenade.m4a",
"class": "classical",
"sentence": "This music is called Pictures at an Exhibition — Promenade.",
"openingBoostDb": 0.05,
"ab": false
},
{
"id": "mussorgsky-unhatched-chicks",
"file": "mussorgsky-unhatched-chicks.m4a",
"class": "classical",
"sentence": "This music is called Ballet of the Unhatched Chicks.",
"openingBoostDb": 0.52,
"ab": false
},
{
"id": "mussorgsky-night-bald-mountain",
"file": "mussorgsky-night-bald-mountain.m4a",
"class": "classical",
"sentence": "This music is called Night on Bald Mountain.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "rimsky-flight-bumblebee",
"file": "rimsky-flight-bumblebee.m4a",
"class": "classical",
"sentence": "This music is called Flight of the Bumblebee.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "rimsky-scheherazade-opening",
"file": "rimsky-scheherazade-opening.m4a",
"class": "classical",
"sentence": "This music is called Scheherazade — opening.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "strauss-blue-danube",
"file": "strauss-blue-danube.m4a",
"class": "classical",
"sentence": "This music is called The Blue Danube.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "strauss-tritsch-tratsch-polka",
"file": "strauss-tritsch-tratsch-polka.m4a",
"class": "classical",
"sentence": "This music is called Tritsch-Tratsch-Polka.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "bizet-habanera",
"file": "bizet-habanera.m4a",
"class": "classical",
"sentence": "This music is called Carmen — Habanera.",
"openingBoostDb": 1.01,
"ab": false
},
{
"id": "bizet-toreador-song",
"file": "bizet-toreador-song.m4a",
"class": "classical",
"sentence": "This music is called Carmen — Toreador Song.",
"openingBoostDb": 0.16,
"ab": false
},
{
"id": "rossini-william-tell-finale",
"file": "rossini-william-tell-finale.m4a",
"class": "classical",
"sentence": "This music is called William Tell Overture — finale.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "rossini-barber-seville-overture",
"file": "rossini-barber-seville-overture.m4a",
"class": "classical",
"sentence": "This music is called The Barber of Seville — overture.",
"beforePeakGapDb": -7.85,
"afterPeakGapDb": -2.77,
"openingBoostDb": 5.37,
"ab": true
},
{
"id": "debussy-clair-de-lune",
"file": "debussy-clair-de-lune.m4a",
"class": "classical",
"sentence": "This music is called Clair de lune.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "debussy-arabesque-1",
"file": "debussy-arabesque-1.m4a",
"class": "classical",
"sentence": "This music is called Arabesque No. 1.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "debussy-little-shepherd",
"file": "debussy-little-shepherd.m4a",
"class": "classical",
"sentence": "This music is called The Little Shepherd.",
"openingBoostDb": 2.56,
"ab": false
},
{
"id": "satie-gymnopedie-1",
"file": "satie-gymnopedie-1.m4a",
"class": "classical",
"sentence": "This music is called Gymnopédie No. 1.",
"openingBoostDb": 2.89,
"ab": false
},
{
"id": "joplin-entertainer",
"file": "joplin-entertainer.m4a",
"class": "classical",
"sentence": "This music is called The Entertainer.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "joplin-maple-leaf-rag",
"file": "joplin-maple-leaf-rag.m4a",
"class": "classical",
"sentence": "This music is called Maple Leaf Rag.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "holst-jupiter",
"file": "holst-jupiter.m4a",
"class": "classical",
"sentence": "This music is called The Planets — Jupiter.",
"openingBoostDb": 3.67,
"ab": false
},
{
"id": "holst-mars",
"file": "holst-mars.m4a",
"class": "classical",
"sentence": "This music is called The Planets — Mars.",
"openingBoostDb": 2.1,
"ab": false
},
{
"id": "composer-beethoven",
"file": "composer-beethoven.m4a",
"class": "composer",
"sentence": "This composer is called Ludwig van Beethoven.",
"openingBoostDb": 1.14,
"ab": false
},
{
"id": "composer-mozart",
"file": "composer-mozart.m4a",
"class": "composer",
"sentence": "This composer is called Wolfgang Amadeus Mozart.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "composer-tchaikovsky",
"file": "composer-tchaikovsky.m4a",
"class": "composer",
"sentence": "This composer is called Pyotr Ilyich Tchaikovsky.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "composer-traditional",
"file": "composer-traditional.m4a",
"class": "composer",
"sentence": "These are traditional songs.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "composer-bach",
"file": "composer-bach.m4a",
"class": "composer",
"sentence": "This composer is called Johann Sebastian Bach.",
"openingBoostDb": 0.29,
"ab": false
},
{
"id": "composer-vivaldi",
"file": "composer-vivaldi.m4a",
"class": "composer",
"sentence": "This composer is called Antonio Vivaldi.",
"openingBoostDb": 2.11,
"ab": false
},
{
"id": "composer-handel",
"file": "composer-handel.m4a",
"class": "composer",
"sentence": "This composer is called George Frideric Handel.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "composer-pachelbel",
"file": "composer-pachelbel.m4a",
"class": "composer",
"sentence": "This composer is called Johann Pachelbel.",
"openingBoostDb": 3.38,
"ab": false
},
{
"id": "composer-haydn",
"file": "composer-haydn.m4a",
"class": "composer",
"sentence": "This composer is called Joseph Haydn.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "composer-schubert",
"file": "composer-schubert.m4a",
"class": "composer",
"sentence": "This composer is called Franz Schubert.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "composer-mendelssohn",
"file": "composer-mendelssohn.m4a",
"class": "composer",
"sentence": "This composer is called Felix Mendelssohn.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "composer-chopin",
"file": "composer-chopin.m4a",
"class": "composer",
"sentence": "This composer is called Frédéric Chopin.",
"beforePeakGapDb": -7.44,
"afterPeakGapDb": -1.85,
"openingBoostDb": 5.46,
"ab": true
},
{
"id": "composer-schumann",
"file": "composer-schumann.m4a",
"class": "composer",
"sentence": "This composer is called Robert Schumann.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "composer-brahms",
"file": "composer-brahms.m4a",
"class": "composer",
"sentence": "This composer is called Johannes Brahms.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "composer-saint-saens",
"file": "composer-saint-saens.m4a",
"class": "composer",
"sentence": "This composer is called Camille Saint-Saëns.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "composer-grieg",
"file": "composer-grieg.m4a",
"class": "composer",
"sentence": "This composer is called Edvard Grieg.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "composer-dvorak",
"file": "composer-dvorak.m4a",
"class": "composer",
"sentence": "This composer is called Antonín Dvořák.",
"openingBoostDb": 3.89,
"ab": false
},
{
"id": "composer-mussorgsky",
"file": "composer-mussorgsky.m4a",
"class": "composer",
"sentence": "This composer is called Modest Mussorgsky.",
"openingBoostDb": 1.68,
"ab": false
},
{
"id": "composer-rimsky-korsakov",
"file": "composer-rimsky-korsakov.m4a",
"class": "composer",
"sentence": "This composer is called Nikolai Rimsky-Korsakov.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "composer-strauss",
"file": "composer-strauss.m4a",
"class": "composer",
"sentence": "This composer is called Johann Strauss the Second.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "composer-bizet",
"file": "composer-bizet.m4a",
"class": "composer",
"sentence": "This composer is called Georges Bizet.",
"beforePeakGapDb": -8.07,
"afterPeakGapDb": -2.06,
"openingBoostDb": 5.99,
"ab": true
},
{
"id": "composer-rossini",
"file": "composer-rossini.m4a",
"class": "composer",
"sentence": "This composer is called Gioachino Rossini.",
"beforePeakGapDb": -7.04,
"afterPeakGapDb": -2.08,
"openingBoostDb": 5.09,
"ab": true
},
{
"id": "composer-debussy",
"file": "composer-debussy.m4a",
"class": "composer",
"sentence": "This composer is called Claude Debussy.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "composer-satie",
"file": "composer-satie.m4a",
"class": "composer",
"sentence": "This composer is called Erik Satie.",
"openingBoostDb": 0.0,
"ab": false
},
{
"id": "composer-joplin",
"file": "composer-joplin.m4a",
"class": "composer",
"sentence": "This composer is called Scott Joplin.",
"openingBoostDb": 0.95,
"ab": false
},
{
"id": "composer-holst",
"file": "composer-holst.m4a",
"class": "composer",
"sentence": "This composer is called Gustav Holst.",
"openingBoostDb": 0.0,
"ab": false
}
];
