/* generated by word-book/tools/extract-sentence-batch.py -- do not hand-edit */
window.SENTENCE_EXTRACT = {
 "why": "A/B/C listening set built by word-book/tools/extract-sentence-batch.py. A is a byte copy of the shipped clip, B is cut from the paid sentence master, C is that master. Flags and ASR are context for the listener, never verdicts.",
 "cards": [
  {
   "sense": "arrive.reach-a-place",
   "word": "arrive",
   "sentence": "We arrive at school before the bell.",
   "A": {
    "file": "audio/arrive.reach-a-place.A.m4a",
    "source": "word-book/audio/words/arrive.m4a",
    "sha256": "e691d8f205e96cf63e8a1fe39fa9b04bf635378f71eb0ed117356139063b390b"
   },
   "B": {
    "file": "audio/arrive.reach-a-place.B.m4a",
    "sha256": "88911eddeb490950de5ec62f241243f0c40eedae5daf5da2c89f3101512431b3",
    "note": null
   },
   "C": {
    "file": "audio/arrive.reach-a-place.C.m4a",
    "master": "word-book/audio-source/sentences/arrive.reach-a-place.mp3",
    "master_sha256": "1ba4f1d266ada26cbc03dc2ab334e76cee16d70353e4674c7be3fdf787ca68e4"
   },
   "cut_s": [
    0.1966,
    0.476
   ],
   "raw_alignment_span_s": [
    0.197,
    0.476
   ],
   "edge_rule": [
    "raw",
    "raw"
   ],
   "energy_dbfs_at_cut": [
    -15.5,
    -30.6
   ],
   "word_index": 1,
   "words_in_sentence": 7,
   "flags": [
    {
     "flag": "edge-in-speech",
     "why": "the start cut sits at -15.5 dBFS, above -35: inside speech, so clipped or smeared"
    },
    {
     "flag": "edge-in-speech",
     "why": "the end cut sits at -30.6 dBFS, above -35: inside speech, so clipped or smeared"
    }
   ],
   "report": "arrive.reach-a-place.report.json",
   "asr_triage": {
    "label": "TRIAGE ONLY -- not pronunciation QA (owner rule 2026-09-23)",
    "heard": {
     "A": [
      "Arriva.",
      "Arriva."
     ],
     "B": [
      "arrived.",
      "arrived."
     ],
     "C": [
      "We arrive at school before the bell.",
      "We arrive at school before the bell."
     ]
    },
    "A_reads_as_headword": false,
    "B_reads_as_headword": false,
    "A_B_agree": false,
    "asr_adds_to_listening_set": true
   }
  },
  {
   "sense": "bake.cook-in-oven",
   "word": "bake",
   "sentence": "We bake biscuits shaped like stars.",
   "A": {
    "file": "audio/bake.cook-in-oven.A.m4a",
    "source": "word-book/audio/words/bake.m4a",
    "sha256": "ff87b3e8515f037707a3c618b2cb60cd22001a2645d2d95381b87237ac1c05f0"
   },
   "B": {
    "file": "audio/bake.cook-in-oven.B.m4a",
    "sha256": "4cab9836f1f87fa25ac258181831537c58f8cb342a81d7461b978a540989deff",
    "note": "byte copy of /private/tmp/claude-501/-Users-veeranuchleelalai-git-repos-children-games/5beeeded-44b5-4ae7-b8a3-bf93b5644175/scratchpad/bake-B-judged.m4a, the B the owner already judged; the re-made cut decodes to identical samples"
   },
   "C": {
    "file": "audio/bake.cook-in-oven.C.m4a",
    "master": "word-book/audio-source/sentences/bake.cook-in-oven.mp3",
    "master_sha256": "0b9fdf06758f8409581a4ab10439c6e8c9de357e8587635adef854e234ef0c6c"
   },
   "cut_s": [
    0.2193,
    0.496
   ],
   "raw_alignment_span_s": [
    0.232,
    0.441
   ],
   "edge_rule": [
    "dip",
    "dip"
   ],
   "energy_dbfs_at_cut": [
    -60.1,
    -67.7
   ],
   "word_index": 1,
   "words_in_sentence": 6,
   "flags": [
    {
     "flag": "unreleased-stop",
     "why": "ends in a stop before 'biscuits' (a consonant): usually unreleased in connected speech",
     "release_measured": false,
     "measurement": "110 ms of closure before the cut, no release above it"
    }
   ],
   "report": "bake.cook-in-oven.report.json",
   "asr_triage": {
    "label": "TRIAGE ONLY -- not pronunciation QA (owner rule 2026-09-23)",
    "heard": {
     "A": [
      "Back eight.",
      "Back eight."
     ],
     "B": [
      "Like.",
      "Like."
     ],
     "C": [
      "We bake biscuits shaped like stars.",
      "We bake biscuits shaped like stars."
     ]
    },
    "A_reads_as_headword": false,
    "B_reads_as_headword": false,
    "A_B_agree": false,
    "asr_adds_to_listening_set": true
   }
  },
  {
   "sense": "be.exist-or-have-a-quality",
   "word": "be",
   "sentence": "I want to be an astronaut.",
   "A": {
    "file": "audio/be.exist-or-have-a-quality.A.m4a",
    "source": "word-book/audio/words/be.m4a",
    "sha256": "84fb03635572f5d36b2cca530973460e54cbd96beebbbbd0b432f7a82eb161ec"
   },
   "B": {
    "file": "audio/be.exist-or-have-a-quality.B.m4a",
    "sha256": "eb1f3753d7d668cd07d31dbf69d494bbde04f5a311d1a09d2308359c69abc19c",
    "note": null
   },
   "C": {
    "file": "audio/be.exist-or-have-a-quality.C.m4a",
    "master": "word-book/audio-source/sentences/be.exist-or-have-a-quality.mp3",
    "master_sha256": "aa2cf20365895df59c257b704b7e5fcb8f91a1afec219e478edc114cbaf2ba28"
   },
   "cut_s": [
    0.5002,
    0.6168
   ],
   "raw_alignment_span_s": [
    0.499,
    0.592
   ],
   "edge_rule": [
    "dip",
    "gap-min"
   ],
   "energy_dbfs_at_cut": [
    -52.0,
    -24.9
   ],
   "word_index": 3,
   "words_in_sentence": 6,
   "flags": [
    {
     "flag": "function-word",
     "why": "a closed-class word; in a sentence it is often a weak, reduced form"
    },
    {
     "flag": "edge-in-speech",
     "why": "the end cut sits at -24.9 dBFS, above -35: inside speech, so clipped or smeared"
    }
   ],
   "report": "be.exist-or-have-a-quality.report.json",
   "asr_triage": {
    "label": "TRIAGE ONLY -- not pronunciation QA (owner rule 2026-09-23)",
    "heard": {
     "A": [
      "The...",
      "The..."
     ],
     "B": [
      "",
      ""
     ],
     "C": [
      "I want to be an astronaut.",
      "I want to be an astronaut."
     ]
    },
    "A_reads_as_headword": false,
    "B_reads_as_headword": false,
    "A_B_agree": false,
    "asr_adds_to_listening_set": true
   }
  },
  {
   "sense": "best.highest-quality",
   "word": "best",
   "sentence": "This is the best spot for our picnic.",
   "A": {
    "file": "audio/best.highest-quality.A.m4a",
    "source": "word-book/audio/words/best.m4a",
    "sha256": "39793e0ac15da7946929ea8fe2f51f830c270ab9c2b83c1e2181db60d79a790d"
   },
   "B": {
    "file": "audio/best.highest-quality.B.m4a",
    "sha256": "1ff88e7446a9c7d874af9bbffe3287a29714c8134423b8c1f00a1c7747f74ff1",
    "note": null
   },
   "C": {
    "file": "audio/best.highest-quality.C.m4a",
    "master": "word-book/audio-source/sentences/best.highest-quality.mp3",
    "master_sha256": "ff68321f082a8297d741cd1f5af911b1b32d32db54e2000dd16a62b779bb9804"
   },
   "cut_s": [
    0.5325,
    0.8318
   ],
   "raw_alignment_span_s": [
    0.534,
    0.766
   ],
   "edge_rule": [
    "dip",
    "dip"
   ],
   "energy_dbfs_at_cut": [
    -75.2,
    -46.7
   ],
   "word_index": 3,
   "words_in_sentence": 8,
   "flags": [
    {
     "flag": "unreleased-stop",
     "why": "ends in a stop before 'spot' (a consonant): usually unreleased in connected speech",
     "release_measured": false,
     "measurement": "10 ms of closure before the cut, no release above it"
    }
   ],
   "report": "best.highest-quality.report.json",
   "asr_triage": {
    "label": "TRIAGE ONLY -- not pronunciation QA (owner rule 2026-09-23)",
    "heard": {
     "A": [
      "If the best...",
      "If the best..."
     ],
     "B": [
      "Best.",
      "Best."
     ],
     "C": [
      "This is the best spot for our picnic.",
      "This is the best spot for our picnic."
     ]
    },
    "A_reads_as_headword": false,
    "B_reads_as_headword": true,
    "A_B_agree": false,
    "asr_adds_to_listening_set": true
   }
  },
  {
   "sense": "bone.body-part",
   "word": "bone",
   "sentence": "The doctor shows us a picture of a bone.",
   "A": {
    "file": "audio/bone.body-part.A.m4a",
    "source": "word-book/audio/words/bone.m4a",
    "sha256": "12eb5abd1f64f5c49254781965fe19ab69ad7c83c7cd7cfc0d59f694abaa4038"
   },
   "B": {
    "file": "audio/bone.body-part.B.m4a",
    "sha256": "013cdf145b1a761a56a58feaaf772f442cf5002679ae00a6a92b9980bcc24d7c",
    "note": null
   },
   "C": {
    "file": "audio/bone.body-part.C.m4a",
    "master": "word-book/audio-source/sentences/bone.body-part.mp3",
    "master_sha256": "0951ae9ea847a2fb444ee3d7ce6ca94f6450f39c1807d118f1ace96258b93ff0"
   },
   "cut_s": [
    1.5279,
    1.992
   ],
   "raw_alignment_span_s": [
    1.521,
    1.927
   ],
   "edge_rule": [
    "dip",
    "decay"
   ],
   "energy_dbfs_at_cut": [
    -81.2,
    -70.4
   ],
   "word_index": 8,
   "words_in_sentence": 9,
   "flags": [
    {
     "flag": "sentence-final",
     "why": "the last word of the sentence: terminal fall, and B ends in its decay"
    }
   ],
   "report": "bone.body-part.report.json",
   "asr_triage": {
    "label": "TRIAGE ONLY -- not pronunciation QA (owner rule 2026-09-23)",
    "heard": {
     "A": [
      "Bow nate.",
      "Bow nate."
     ],
     "B": [
      "Bone.",
      "Bone."
     ],
     "C": [
      "The doctor shows us a picture of a bone.",
      "The doctor shows us a picture of a bone."
     ]
    },
    "A_reads_as_headword": false,
    "B_reads_as_headword": true,
    "A_B_agree": false,
    "asr_adds_to_listening_set": true
   }
  },
  {
   "sense": "bun.food",
   "word": "bun",
   "sentence": "I choose a soft round bun.",
   "A": {
    "file": "audio/bun.food.A.m4a",
    "source": "word-book/audio/words/bun.m4a",
    "sha256": "ab49f129f5d1bf10156d86fabbb9dac9dfc6cd2c0c00d0993f27fcade682b5d6"
   },
   "B": {
    "file": "audio/bun.food.B.m4a",
    "sha256": "2ee9255f146dbf11710606ad84d1c9f617311caba29864d50858b3348602be41",
    "note": null
   },
   "C": {
    "file": "audio/bun.food.C.m4a",
    "master": "word-book/audio-source/sentences/bun.food.mp3",
    "master_sha256": "5a45087a27dabe57c195a901725630731ef2b7b812a40c4a6f00fc3a62a3678d"
   },
   "cut_s": [
    1.262,
    1.6702
   ],
   "raw_alignment_span_s": [
    1.242,
    1.614
   ],
   "edge_rule": [
    "dip",
    "decay"
   ],
   "energy_dbfs_at_cut": [
    -80.6,
    -63.1
   ],
   "word_index": 5,
   "words_in_sentence": 6,
   "flags": [
    {
     "flag": "sentence-final",
     "why": "the last word of the sentence: terminal fall, and B ends in its decay"
    }
   ],
   "report": "bun.food.report.json",
   "asr_triage": {
    "label": "TRIAGE ONLY -- not pronunciation QA (owner rule 2026-09-23)",
    "heard": {
     "A": [
      "Boone.",
      "Boone."
     ],
     "B": [
      "Fun.",
      "Fun."
     ],
     "C": [
      "I choose a soft round bun.",
      "I choose a soft round bun."
     ]
    },
    "A_reads_as_headword": false,
    "B_reads_as_headword": false,
    "A_B_agree": false,
    "asr_adds_to_listening_set": true
   }
  },
  {
   "sense": "base.bottom-support",
   "word": "base",
   "sentence": "The rocket waits on its launch base.",
   "A": {
    "file": "audio/base.bottom-support.A.m4a",
    "source": "word-book/audio/words/base.m4a",
    "sha256": "1009384bc1a4bb8c9e08120774ccc8671e8a9b1d4e390e1d0b77544eb546aad5"
   },
   "B": {
    "file": "audio/base.bottom-support.B.m4a",
    "sha256": "f4b5bf0b29a781998ddb44de2e19a92b4b4ed4ddb833b04531aa89291784ad90",
    "note": null
   },
   "C": {
    "file": "audio/base.bottom-support.C.m4a",
    "master": "word-book/audio-source/sentences/base.bottom-support.mp3",
    "master_sha256": "9e0f789970ebbda922fb65944b4d6cae56df165f3306bc1f660a7f0efade6f6f"
   },
   "cut_s": [
    1.5783,
    2.0615
   ],
   "raw_alignment_span_s": [
    1.579,
    1.974
   ],
   "edge_rule": [
    "dip",
    "decay"
   ],
   "energy_dbfs_at_cut": [
    -52.4,
    -67.3
   ],
   "word_index": 6,
   "words_in_sentence": 7,
   "flags": [
    {
     "flag": "sentence-final",
     "why": "the last word of the sentence: terminal fall, and B ends in its decay"
    }
   ],
   "report": "base.bottom-support.report.json",
   "asr_triage": {
    "label": "TRIAGE ONLY -- not pronunciation QA (owner rule 2026-09-23)",
    "heard": {
     "A": [
      "Basie.",
      "Basie."
     ],
     "B": [
      "base.",
      "base."
     ],
     "C": [
      "The rocket waits on its launch base.",
      "The rocket waits on its launch base."
     ]
    },
    "A_reads_as_headword": false,
    "B_reads_as_headword": true,
    "A_B_agree": false,
    "asr_adds_to_listening_set": true
   }
  },
  {
   "sense": "car.road-vehicle",
   "word": "car",
   "sentence": "Dad parks the car beside the library.",
   "A": {
    "file": "audio/car.road-vehicle.A.m4a",
    "source": "word-book/audio/words/car.m4a",
    "sha256": "a7506ef3c5b854d9147274dc01587bee41391d9ad5d076916395fafb184c6f48"
   },
   "B": {
    "file": "audio/car.road-vehicle.B.m4a",
    "sha256": "ef7754ca881706601f174bec8272b5b562a3018be4fb156cba359d1c25ed0a1d",
    "note": null
   },
   "C": {
    "file": "audio/car.road-vehicle.C.m4a",
    "master": "word-book/audio-source/sentences/car.road-vehicle.mp3",
    "master_sha256": "0170e59ac7c2700ac9b6a388239c84fe78406dcc35923bff78c85a1a9a3aa5f4"
   },
   "cut_s": [
    0.8062,
    1.0904
   ],
   "raw_alignment_span_s": [
    0.836,
    1.033
   ],
   "edge_rule": [
    "dip",
    "dip"
   ],
   "energy_dbfs_at_cut": [
    -61.8,
    -51.9
   ],
   "word_index": 3,
   "words_in_sentence": 7,
   "flags": [],
   "report": "car.road-vehicle.report.json",
   "asr_triage": {
    "label": "TRIAGE ONLY -- not pronunciation QA (owner rule 2026-09-23)",
    "heard": {
     "A": [
      "Cal.",
      "Cal."
     ],
     "B": [
      "Car...",
      "Car..."
     ],
     "C": [
      "Dad parks the car beside the library.",
      "Dad parks the car beside the library."
     ]
    },
    "A_reads_as_headword": false,
    "B_reads_as_headword": true,
    "A_B_agree": false,
    "asr_adds_to_listening_set": true
   }
  },
  {
   "sense": "caravan.travelling-home",
   "word": "caravan",
   "sentence": "Our caravan has a tiny kitchen.",
   "A": {
    "file": "audio/caravan.travelling-home.A.m4a",
    "source": "word-book/audio/words/caravan.m4a",
    "sha256": "96bee248ba3fef355fee0c8cc90b63b00cb49b255665f47747cdb176a54b9fd5"
   },
   "B": {
    "file": "audio/caravan.travelling-home.B.m4a",
    "sha256": "7bae52e52062aa2ea1c3429e5f74e4ff7ec8ec84e41d01eff5839b895fa48833",
    "note": null
   },
   "C": {
    "file": "audio/caravan.travelling-home.C.m4a",
    "master": "word-book/audio-source/sentences/caravan.travelling-home.mp3",
    "master_sha256": "00b5426127749b8de5efbe4a9d4d81d442f400bb696d76d682908b43b9479e23"
   },
   "cut_s": [
    0.213,
    0.7847
   ],
   "raw_alignment_span_s": [
    0.244,
    0.72
   ],
   "edge_rule": [
    "dip",
    "gap-min"
   ],
   "energy_dbfs_at_cut": [
    -65.7,
    -29.0
   ],
   "word_index": 1,
   "words_in_sentence": 6,
   "flags": [
    {
     "flag": "edge-in-speech",
     "why": "the end cut sits at -29.0 dBFS, above -35: inside speech, so clipped or smeared"
    }
   ],
   "report": "caravan.travelling-home.report.json",
   "asr_triage": {
    "label": "TRIAGE ONLY -- not pronunciation QA (owner rule 2026-09-23)",
    "heard": {
     "A": [
      "Che caravan.",
      "Che caravan."
     ],
     "B": [
      "Caravan...",
      "Caravan..."
     ],
     "C": [
      "Our caravan has a tiny kitchen.",
      "Our caravan has a tiny kitchen."
     ]
    },
    "A_reads_as_headword": false,
    "B_reads_as_headword": true,
    "A_B_agree": false,
    "asr_adds_to_listening_set": true
   }
  },
  {
   "sense": "care.be-concerned",
   "word": "care",
   "sentence": "We care about the animals in our garden.",
   "A": {
    "file": "audio/care.be-concerned.A.m4a",
    "source": "word-book/audio/words/care.m4a",
    "sha256": "98f060bc677e961f2fc3ff16545c31dec8947a6aaf812713b6b48e6942deef20"
   },
   "B": {
    "file": "audio/care.be-concerned.B.m4a",
    "sha256": "1af8a95eefbe3360dab9a5da3c26a659ea2713dedf6fc898cef9f40d67f4c2f5",
    "note": null
   },
   "C": {
    "file": "audio/care.be-concerned.C.m4a",
    "master": "word-book/audio-source/sentences/care.be-concerned.mp3",
    "master_sha256": "8784869b90e9ae15982906ab5778ddd6632c3097d5d67c3100b771dd85fd81e6"
   },
   "cut_s": [
    0.2165,
    0.4758
   ],
   "raw_alignment_span_s": [
    0.232,
    0.476
   ],
   "edge_rule": [
    "dip",
    "raw"
   ],
   "energy_dbfs_at_cut": [
    -64.9,
    -18.4
   ],
   "word_index": 1,
   "words_in_sentence": 8,
   "flags": [
    {
     "flag": "edge-in-speech",
     "why": "the end cut sits at -18.4 dBFS, above -35: inside speech, so clipped or smeared"
    }
   ],
   "report": "care.be-concerned.report.json",
   "asr_triage": {
    "label": "TRIAGE ONLY -- not pronunciation QA (owner rule 2026-09-23)",
    "heard": {
     "A": [
      "Got a...",
      "Got a..."
     ],
     "B": [
      "Karen.",
      "Karen."
     ],
     "C": [
      "We care about the animals in our garden.",
      "We care about the animals in our garden."
     ]
    },
    "A_reads_as_headword": false,
    "B_reads_as_headword": false,
    "A_B_agree": false,
    "asr_adds_to_listening_set": true
   }
  },
  {
   "sense": "chop.cut-into-pieces",
   "word": "chop",
   "sentence": "Dad helps me chop the vegetables.",
   "A": {
    "file": "audio/chop.cut-into-pieces.A.m4a",
    "source": "word-book/audio/words/chop.m4a",
    "sha256": "a97399137cea4c8b9217eedeee9491571b45fdb4bf64089351d3e44e4ec6a712"
   },
   "B": {
    "file": "audio/chop.cut-into-pieces.B.m4a",
    "sha256": "b1ded8587cf3fac0a8fb2f79ae8a95e0fe067e97469ae081bf72a234b9b4c762",
    "note": null
   },
   "C": {
    "file": "audio/chop.cut-into-pieces.C.m4a",
    "master": "word-book/audio-source/sentences/chop.cut-into-pieces.mp3",
    "master_sha256": "183afa965212a4ddf4018a3190cc0ce950bf4bdfd589b40be392d5b61c4aa68c"
   },
   "cut_s": [
    0.7473,
    0.989
   ],
   "raw_alignment_span_s": [
    0.755,
    0.964
   ],
   "edge_rule": [
    "dip",
    "dip"
   ],
   "energy_dbfs_at_cut": [
    -60.7,
    -64.8
   ],
   "word_index": 3,
   "words_in_sentence": 6,
   "flags": [
    {
     "flag": "unreleased-stop",
     "why": "ends in a stop before 'the' (a consonant): usually unreleased in connected speech",
     "release_measured": true,
     "measurement": "release at 0.850 s (-24 dBFS over a -40 dBFS closure)"
    }
   ],
   "report": "chop.cut-into-pieces.report.json",
   "asr_triage": {
    "label": "TRIAGE ONLY -- not pronunciation QA (owner rule 2026-09-23)",
    "heard": {
     "A": [
      "Shopping.",
      "Shopping."
     ],
     "B": [
      "Chump.",
      "Chump."
     ],
     "C": [
      "Dad helps me chop the vegetables.",
      "Dad helps me chop the vegetables."
     ]
    },
    "A_reads_as_headword": false,
    "B_reads_as_headword": false,
    "A_B_agree": false,
    "asr_adds_to_listening_set": true
   }
  },
  {
   "sense": "cone.solid-shape",
   "word": "cone",
   "sentence": "The party hat looks like a cone.",
   "A": {
    "file": "audio/cone.solid-shape.A.m4a",
    "source": "word-book/audio/words/cone.m4a",
    "sha256": "9227146aadc45ca1e46afdb8903c00a20d6485d19efe34202a3f3301103e2e32"
   },
   "B": {
    "file": "audio/cone.solid-shape.B.m4a",
    "sha256": "216f0bd985a828c52e04f84cbda73265321379c1430eef1aa4ae2ba0f49b6730",
    "note": null
   },
   "C": {
    "file": "audio/cone.solid-shape.C.m4a",
    "master": "word-book/audio-source/sentences/cone.solid-shape.mp3",
    "master_sha256": "505838d72595126c4af1c7679c34e714332fc7ac74fedd2287aef97da0dc2e6e"
   },
   "cut_s": [
    1.1745,
    1.6658
   ],
   "raw_alignment_span_s": [
    1.207,
    1.649
   ],
   "edge_rule": [
    "dip",
    "decay"
   ],
   "energy_dbfs_at_cut": [
    -69.5,
    -58.6
   ],
   "word_index": 6,
   "words_in_sentence": 7,
   "flags": [
    {
     "flag": "sentence-final",
     "why": "the last word of the sentence: terminal fall, and B ends in its decay"
    }
   ],
   "report": "cone.solid-shape.report.json",
   "asr_triage": {
    "label": "TRIAGE ONLY -- not pronunciation QA (owner rule 2026-09-23)",
    "heard": {
     "A": [
      "Conet.",
      "Conet."
     ],
     "B": [
      "Cone.",
      "Cone."
     ],
     "C": [
      "The party hat looks like a cone.",
      "The party hat looks like a cone."
     ]
    },
    "A_reads_as_headword": false,
    "B_reads_as_headword": true,
    "A_B_agree": false,
    "asr_adds_to_listening_set": true
   }
  },
  {
   "sense": "connect.link",
   "word": "connect",
   "sentence": "We connect two tubes to build our model space station.",
   "A": {
    "file": "audio/connect.link.A.m4a",
    "source": "word-book/audio/words/connect.m4a",
    "sha256": "31d6f6bce31a299fbb1edb9c7b8d3dd1f4034923832889d724e25c2d13037e5e"
   },
   "B": {
    "file": "audio/connect.link.B.m4a",
    "sha256": "73aa304266acb462d3d40c6bc0fc9dda91bc9ef8809be94dbc162a6eaab3c01c",
    "note": null
   },
   "C": {
    "file": "audio/connect.link.C.m4a",
    "master": "word-book/audio-source/sentences/connect.link.mp3",
    "master_sha256": "fbb68fda6641a55095bae3dacdf70c3cd3640adccd96ba7167ea4ed14f7fe146"
   },
   "cut_s": [
    0.2326,
    0.5835
   ],
   "raw_alignment_span_s": [
    0.232,
    0.546
   ],
   "edge_rule": [
    "dip",
    "dip"
   ],
   "energy_dbfs_at_cut": [
    -57.9,
    -61.9
   ],
   "word_index": 1,
   "words_in_sentence": 10,
   "flags": [
    {
     "flag": "unreleased-stop",
     "why": "ends in a stop before 'two' (a consonant): usually unreleased in connected speech",
     "release_measured": false,
     "measurement": "108 ms of closure before the cut, no release above it"
    }
   ],
   "report": "connect.link.report.json",
   "asr_triage": {
    "label": "TRIAGE ONLY -- not pronunciation QA (owner rule 2026-09-23)",
    "heard": {
     "A": [
      "Cool connect.",
      "Cool connect."
     ],
     "B": [
      "Connect.",
      "Connect."
     ],
     "C": [
      "We connect 2 tubes to build our model space station.",
      "We connect 2 tubes to build our model space station."
     ]
    },
    "A_reads_as_headword": false,
    "B_reads_as_headword": true,
    "A_B_agree": false,
    "asr_adds_to_listening_set": true
   }
  },
  {
   "sense": "costume.dress-up-clothes",
   "word": "costume",
   "sentence": "My costume makes me look like an astronaut.",
   "A": {
    "file": "audio/costume.dress-up-clothes.A.m4a",
    "source": "word-book/audio/words/costume.m4a",
    "sha256": "cc54cf1fd9609b15de23bb98877b517d6b6d2e26b022ca6abbfdd6756d2eb777"
   },
   "B": {
    "file": "audio/costume.dress-up-clothes.B.m4a",
    "sha256": "d0f6a47cd5c16936d7821701c9c1051abdb71d68aa78d88ab15d63512a1f1cc2",
    "note": null
   },
   "C": {
    "file": "audio/costume.dress-up-clothes.C.m4a",
    "master": "word-book/audio-source/sentences/costume.dress-up-clothes.mp3",
    "master_sha256": "2726f8ad3c32fa05711254dcd131a6cb9441832351a73928f023dee052a3cb46"
   },
   "cut_s": [
    0.2208,
    0.6261
   ],
   "raw_alignment_span_s": [
    0.232,
    0.627
   ],
   "edge_rule": [
    "dip",
    "raw"
   ],
   "energy_dbfs_at_cut": [
    -61.8,
    -28.3
   ],
   "word_index": 1,
   "words_in_sentence": 8,
   "flags": [
    {
     "flag": "edge-in-speech",
     "why": "the end cut sits at -28.3 dBFS, above -35: inside speech, so clipped or smeared"
    }
   ],
   "report": "costume.dress-up-clothes.report.json",
   "asr_triage": {
    "label": "TRIAGE ONLY -- not pronunciation QA (owner rule 2026-09-23)",
    "heard": {
     "A": [
      "Costume.",
      "Costume."
     ],
     "B": [
      "Costume.",
      "Costume."
     ],
     "C": [
      "My costume makes me look like an astronaut.",
      "My costume makes me look like an astronaut."
     ]
    },
    "A_reads_as_headword": true,
    "B_reads_as_headword": true,
    "A_B_agree": true,
    "asr_adds_to_listening_set": false
   }
  },
  {
   "sense": "cupcake.food",
   "word": "cupcake",
   "sentence": "My cupcake has a pink flower on top.",
   "A": {
    "file": "audio/cupcake.food.A.m4a",
    "source": "word-book/audio/words/cupcake.m4a",
    "sha256": "218e5dac84062c7165a67f90edb64e58376e953739c2aef70ec15a3dac02ae3f"
   },
   "B": {
    "file": "audio/cupcake.food.B.m4a",
    "sha256": "9783bf6f046d40305604054b47980a1d19848646482ec484ccce5e8dd919a0e4",
    "note": null
   },
   "C": {
    "file": "audio/cupcake.food.C.m4a",
    "master": "word-book/audio-source/sentences/cupcake.food.mp3",
    "master_sha256": "a857b161162576cac7112b630723f40df14a9a52ecb011f746d90b4f5fcc215d"
   },
   "cut_s": [
    0.2379,
    0.6875
   ],
   "raw_alignment_span_s": [
    0.255,
    0.685
   ],
   "edge_rule": [
    "dip",
    "dip"
   ],
   "energy_dbfs_at_cut": [
    -60.8,
    -40.9
   ],
   "word_index": 1,
   "words_in_sentence": 8,
   "flags": [
    {
     "flag": "unreleased-stop",
     "why": "ends in a stop before 'has' (a consonant): usually unreleased in connected speech",
     "release_measured": true,
     "measurement": "release at 0.485 s (-37 dBFS over a -68 dBFS closure)"
    }
   ],
   "report": "cupcake.food.report.json",
   "asr_triage": {
    "label": "TRIAGE ONLY -- not pronunciation QA (owner rule 2026-09-23)",
    "heard": {
     "A": [
      "A cupcake.",
      "A cupcake."
     ],
     "B": [
      "Cupcake.",
      "Cupcake."
     ],
     "C": [
      "My cupcake has a pink flower on top.",
      "My cupcake has a pink flower on top."
     ]
    },
    "A_reads_as_headword": false,
    "B_reads_as_headword": true,
    "A_B_agree": false,
    "asr_adds_to_listening_set": true
   }
  },
  {
   "sense": "date.calendar-day",
   "word": "date",
   "sentence": "We write the date at the top of the page.",
   "A": {
    "file": "audio/date.calendar-day.A.m4a",
    "source": "word-book/audio/words/date.m4a",
    "sha256": "421e3febcc503005fd050ba25120fe17bc9d6555a9e56111a1805de15ecb0539"
   },
   "B": {
    "file": "audio/date.calendar-day.B.m4a",
    "sha256": "cc8ad39ca87f8b764d55a0afd0365dfbc7cc29f0508e7921fbcdc8121776fdff",
    "note": null
   },
   "C": {
    "file": "audio/date.calendar-day.C.m4a",
    "master": "word-book/audio-source/sentences/date.calendar-day.mp3",
    "master_sha256": "01d5a5a3c5ddb797a5ddc384065e88af50732a45609726b5111df5d6427c6b5f"
   },
   "cut_s": [
    0.564,
    0.804
   ],
   "raw_alignment_span_s": [
    0.569,
    0.824
   ],
   "edge_rule": [
    "dip",
    "dip"
   ],
   "energy_dbfs_at_cut": [
    -57.8,
    -41.8
   ],
   "word_index": 3,
   "words_in_sentence": 10,
   "flags": [],
   "report": "date.calendar-day.report.json",
   "asr_triage": {
    "label": "TRIAGE ONLY -- not pronunciation QA (owner rule 2026-09-23)",
    "heard": {
     "A": [
      "Dighty.",
      "Dighty."
     ],
     "B": [
      "",
      ""
     ],
     "C": [
      "We write the date at the top of the page.",
      "We write the date at the top of the page."
     ]
    },
    "A_reads_as_headword": false,
    "B_reads_as_headword": false,
    "A_B_agree": false,
    "asr_adds_to_listening_set": true
   }
  },
  {
   "sense": "date.fruit",
   "word": "date",
   "sentence": "I take the stone out of the date.",
   "A": {
    "file": "audio/date.fruit.A.m4a",
    "source": "word-book/audio/words/date.m4a",
    "sha256": "421e3febcc503005fd050ba25120fe17bc9d6555a9e56111a1805de15ecb0539"
   },
   "B": {
    "file": "audio/date.fruit.B.m4a",
    "sha256": "4411ed1410ca37d86d537b428c5b8dbfe1cc03640e49f61b27dc03970d9b3b39",
    "note": null
   },
   "C": {
    "file": "audio/date.fruit.C.m4a",
    "master": "word-book/audio-source/sentences/date.fruit.mp3",
    "master_sha256": "a48c413fa82456281199a10d066fdb328d7ae20a64626c159e8192a3bef79548"
   },
   "cut_s": [
    1.3575,
    1.8001
   ],
   "raw_alignment_span_s": [
    1.37,
    1.765
   ],
   "edge_rule": [
    "dip",
    "decay"
   ],
   "energy_dbfs_at_cut": [
    -62.0,
    -70.3
   ],
   "word_index": 7,
   "words_in_sentence": 8,
   "flags": [
    {
     "flag": "sentence-final",
     "why": "the last word of the sentence: terminal fall, and B ends in its decay"
    }
   ],
   "report": "date.fruit.report.json",
   "asr_triage": {
    "label": "TRIAGE ONLY -- not pronunciation QA (owner rule 2026-09-23)",
    "heard": {
     "A": [
      "Dighty.",
      "Dighty."
     ],
     "B": [
      "date.",
      "date."
     ],
     "C": [
      "I take the stone out of the date.",
      "I take the stone out of the date."
     ]
    },
    "A_reads_as_headword": false,
    "B_reads_as_headword": true,
    "A_B_agree": false,
    "asr_adds_to_listening_set": true
   }
  },
  {
   "sense": "decide.make-a-choice",
   "word": "decide",
   "sentence": "We decide where to build our cardboard castle.",
   "A": {
    "file": "audio/decide.make-a-choice.A.m4a",
    "source": "word-book/audio/words/decide.m4a",
    "sha256": "b5409c1d74787cd6532edb45a04ce111a730f046f1be7b2355189727ffcbbf47"
   },
   "B": {
    "file": "audio/decide.make-a-choice.B.m4a",
    "sha256": "2eb9c99e4390813dfb43a7c7caa92849f7d8cfdfd8ff85313ed3f4aac67cb1ae",
    "note": null
   },
   "C": {
    "file": "audio/decide.make-a-choice.C.m4a",
    "master": "word-book/audio-source/sentences/decide.make-a-choice.mp3",
    "master_sha256": "33bce2b787a3849e53aff5022f9cd158bc62173df6655e777e909f036045f28c"
   },
   "cut_s": [
    0.2389,
    0.7045
   ],
   "raw_alignment_span_s": [
    0.244,
    0.662
   ],
   "edge_rule": [
    "dip",
    "dip"
   ],
   "energy_dbfs_at_cut": [
    -43.0,
    -59.1
   ],
   "word_index": 1,
   "words_in_sentence": 8,
   "flags": [
    {
     "flag": "unreleased-stop",
     "why": "ends in a stop before 'where' (a consonant): usually unreleased in connected speech",
     "release_measured": true,
     "measurement": "release at 0.446 s (-18 dBFS over a -40 dBFS closure)"
    }
   ],
   "report": "decide.make-a-choice.report.json",
   "asr_triage": {
    "label": "TRIAGE ONLY -- not pronunciation QA (owner rule 2026-09-23)",
    "heard": {
     "A": [
      "Deceed it.",
      "Deceed it."
     ],
     "B": [
      "Decide.",
      "Decide."
     ],
     "C": [
      "We decide where to build our cardboard castle.",
      "We decide where to build our cardboard castle."
     ]
    },
    "A_reads_as_headword": false,
    "B_reads_as_headword": true,
    "A_B_agree": false,
    "asr_adds_to_listening_set": true
   }
  },
  {
   "sense": "dew.water-drops",
   "word": "dew",
   "sentence": "Dew sparkles on the spider's web.",
   "A": {
    "file": "audio/dew.water-drops.A.m4a",
    "source": "word-book/audio/words/dew.m4a",
    "sha256": "3fbbdf080d06262496c3b956d00fa8a8587119ad03111c93562b7c68086155bd"
   },
   "B": {
    "file": "audio/dew.water-drops.B.m4a",
    "sha256": "6bdbedbee56cb21b00f243e42671b2de6686274e376c8996e5d7b5b1ef3bd624",
    "note": null
   },
   "C": {
    "file": "audio/dew.water-drops.C.m4a",
    "master": "word-book/audio-source/sentences/dew.water-drops.mp3",
    "master_sha256": "0a0db48db48ceade864204b87051c128b437bd5116d41a17613ca7097163effe"
   },
   "cut_s": [
    0.0,
    0.299
   ],
   "raw_alignment_span_s": [
    0.0,
    0.279
   ],
   "edge_rule": [
    "dip",
    "gap-min"
   ],
   "energy_dbfs_at_cut": [
    -180.0,
    -31.9
   ],
   "word_index": 0,
   "words_in_sentence": 6,
   "flags": [
    {
     "flag": "edge-in-speech",
     "why": "the end cut sits at -31.9 dBFS, above -35: inside speech, so clipped or smeared"
    }
   ],
   "report": "dew.water-drops.report.json",
   "asr_triage": {
    "label": "TRIAGE ONLY -- not pronunciation QA (owner rule 2026-09-23)",
    "heard": {
     "A": [
      "Don't.",
      "Don't."
     ],
     "B": [
      "Do you?",
      "Do you?"
     ],
     "C": [
      "Do sparkles on the spider's web.",
      "Do sparkles on the spider's web."
     ]
    },
    "A_reads_as_headword": false,
    "B_reads_as_headword": false,
    "A_B_agree": false,
    "asr_adds_to_listening_set": true
   }
  },
  {
   "sense": "dice.game-cubes",
   "word": "dice",
   "sentence": "We roll the dice to start the game.",
   "A": {
    "file": "audio/dice.game-cubes.A.m4a",
    "source": "word-book/audio/words/dice.m4a",
    "sha256": "ec2f250ea4f250a1126cffb6bb86affc907846ba50d3f9559ebeba803f6be047"
   },
   "B": {
    "file": "audio/dice.game-cubes.B.m4a",
    "sha256": "58614502e7717b12ec451ac55b07598bf0d92336da184bf7a75be6d817df0bcf",
    "note": null
   },
   "C": {
    "file": "audio/dice.game-cubes.C.m4a",
    "master": "word-book/audio-source/sentences/dice.game-cubes.mp3",
    "master_sha256": "9e5335c793645b47bcd6c8778b615999a56cd4ad89cc11e95c536b18a7d6c895"
   },
   "cut_s": [
    0.6024,
    0.931
   ],
   "raw_alignment_span_s": [
    0.615,
    0.906
   ],
   "edge_rule": [
    "dip",
    "dip"
   ],
   "energy_dbfs_at_cut": [
    -57.9,
    -57.7
   ],
   "word_index": 3,
   "words_in_sentence": 8,
   "flags": [],
   "report": "dice.game-cubes.report.json",
   "asr_triage": {
    "label": "TRIAGE ONLY -- not pronunciation QA (owner rule 2026-09-23)",
    "heard": {
     "A": [
      "DC.",
      "DC."
     ],
     "B": [
      "Dice.",
      "Dice."
     ],
     "C": [
      "We roll the dice to start the game.",
      "We roll the dice to start the game."
     ]
    },
    "A_reads_as_headword": false,
    "B_reads_as_headword": true,
    "A_B_agree": false,
    "asr_adds_to_listening_set": true
   }
  },
  {
   "sense": "dive.go-underwater",
   "word": "dive",
   "sentence": "We watch the mermaid dive below the waves.",
   "A": {
    "file": "audio/dive.go-underwater.A.m4a",
    "source": "word-book/audio/words/dive.m4a",
    "sha256": "ce8a66c027d5a05d1160755657f8b43df10151160dc46ec9b1679f5b276499a7"
   },
   "B": {
    "file": "audio/dive.go-underwater.B.m4a",
    "sha256": "0274fa4bd2cfe096d3e6698defe4c4b85d42cb746a5c443dca86c80b138c9e6e",
    "note": null
   },
   "C": {
    "file": "audio/dive.go-underwater.C.m4a",
    "master": "word-book/audio-source/sentences/dive.go-underwater.mp3",
    "master_sha256": "24cabe5924fcd29d4a4e1f3ebd48155106788f384b6a29a928fc64b5f5ac8f40"
   },
   "cut_s": [
    1.0155,
    1.3925
   ],
   "raw_alignment_span_s": [
    1.033,
    1.335
   ],
   "edge_rule": [
    "dip",
    "dip"
   ],
   "energy_dbfs_at_cut": [
    -76.5,
    -67.3
   ],
   "word_index": 4,
   "words_in_sentence": 8,
   "flags": [],
   "report": "dive.go-underwater.report.json",
   "asr_triage": {
    "label": "TRIAGE ONLY -- not pronunciation QA (owner rule 2026-09-23)",
    "heard": {
     "A": [
      "Diver.",
      "Diver."
     ],
     "B": [
      "Dive.",
      "Dive."
     ],
     "C": [
      "We watch the mermaid dive below the waves.",
      "We watch the mermaid dive below the waves."
     ]
    },
    "A_reads_as_headword": false,
    "B_reads_as_headword": true,
    "A_B_agree": false,
    "asr_adds_to_listening_set": true
   }
  },
  {
   "sense": "explorer.traveller",
   "word": "explorer",
   "sentence": "The explorer follows the river on the map.",
   "A": {
    "file": "audio/explorer.traveller.A.m4a",
    "source": "word-book/audio/words/explorer.m4a",
    "sha256": "93be2cadcb4309696670f6eb3543908f81fbc25569c2354ec56182780ea34636"
   },
   "B": {
    "file": "audio/explorer.traveller.B.m4a",
    "sha256": "5b8da41733ba00cdeb4b6fb08bd88f1ac8377c4e2a8f9a5391abf5187a19ca02",
    "note": null
   },
   "C": {
    "file": "audio/explorer.traveller.C.m4a",
    "master": "word-book/audio-source/sentences/explorer.traveller.mp3",
    "master_sha256": "9ca220869be3ff805fbce942750d360f1c16b9bbc2426b4c650451de6730d7a0"
   },
   "cut_s": [
    0.2476,
    0.836
   ],
   "raw_alignment_span_s": [
    0.221,
    0.766
   ],
   "edge_rule": [
    "dip",
    "dip"
   ],
   "energy_dbfs_at_cut": [
    -39.7,
    -41.0
   ],
   "word_index": 1,
   "words_in_sentence": 8,
   "flags": [],
   "report": "explorer.traveller.report.json",
   "asr_triage": {
    "label": "TRIAGE ONLY -- not pronunciation QA (owner rule 2026-09-23)",
    "heard": {
     "A": [
      "Explorer.",
      "Explorer."
     ],
     "B": [
      "Explorer.",
      "Explorer."
     ],
     "C": [
      "The explorer follows the river on the map.",
      "The explorer follows the river on the map."
     ]
    },
    "A_reads_as_headword": true,
    "B_reads_as_headword": true,
    "A_B_agree": true,
    "asr_adds_to_listening_set": false
   }
  }
 ],
 "not_built": []
};
