/* Reading Tree (reading-app/), published at /reading/. CACHE_NAME is the name the release
   pipeline reads (publish-app.sh stage 5 matches /CACHE_NAME\s*=/); bumping it arms a release.

   v1 2026-10-01: first publication (owner: "pls also promote the bookshelf to the main hub,
   put it on this hub"). The whole app is about 3 MB, so SHELL precaches every shipped file:
   the Bookshelf, the reader, every book's data and art, and every word clip. That keeps a
   book readable offline on the iPad from the first visit. tools/check-reader.mjs fails when
   SHELL and scripts/ship-list.py disagree, in either direction, so a new book or a new word
   clip cannot ship uncached -- add it here and bump CACHE_NAME.

   v2 2026-10-03: book 2, "A World of Gems", joins the shelf (owner: "gems book -> approved.");
   its 13 paintings, book.json and word clips are in SHELL.

   All apps share one origin (veeranuchlee.github.io), so CacheStorage is shared too:
   activate deletes ONLY caches whose name starts with CACHE_PREFIX, never a neighbour's
   (scripts/check-worker-cache-scope.py). A Test Hub copy carries no worker at all
   (scripts/testhub-service-worker.py --strip).

   Navigations carry a query (?book=space-trip, ?from=wordbook), so they are matched with
   ignoreSearch; data and audio requests are matched exactly. */
const CACHE_NAME = 'reading-v5';
const CACHE_PREFIX = 'reading-v';
const SHELL = [
  './',
  './reader/',
  './audio/words/a.m4a',
  './audio/words/across.m4a',
  './audio/words/adds.m4a',
  './audio/words/alive.m4a',
  './audio/words/also.m4a',
  './audio/words/amber.m4a',
  './audio/words/amethyst.m4a',
  './audio/words/and.m4a',
  './audio/words/are.m4a',
  './audio/words/around.m4a',
  './audio/words/asteroids.m4a',
  './audio/words/bands.m4a',
  './audio/words/beautiful.m4a',
  './audio/words/bend.m4a',
  './audio/words/biggest.m4a',
  './audio/words/bits.m4a',
  './audio/words/by.m4a',
  './audio/words/called.m4a',
  './audio/words/can.m4a',
  './audio/words/carbon.m4a',
  './audio/words/catch.m4a',
  './audio/words/catches.m4a',
  './audio/words/clouds.m4a',
  './audio/words/colorful.m4a',
  './audio/words/colors.m4a',
  './audio/words/come.m4a',
  './audio/words/comes.m4a',
  './audio/words/comets.m4a',
  './audio/words/crystal.m4a',
  './audio/words/crystals.m4a',
  './audio/words/cutter.m4a',
  './audio/words/diamond.m4a',
  './audio/words/different.m4a',
  './audio/words/earth.m4a',
  './audio/words/eight.m4a',
  './audio/words/elements.m4a',
  './audio/words/every.m4a',
  './audio/words/explore.m4a',
  './audio/words/faces.m4a',
  './audio/words/facets.m4a',
  './audio/words/fall.m4a',
  './audio/words/fast.m4a',
  './audio/words/fell.m4a',
  './audio/words/fifteen.m4a',
  './audio/words/finished.m4a',
  './audio/words/first.m4a',
  './audio/words/five.m4a',
  './audio/words/flashes.m4a',
  './audio/words/flat.m4a',
  './audio/words/for.m4a',
  './audio/words/form.m4a',
  './audio/words/from.m4a',
  './audio/words/gauge.m4a',
  './audio/words/gem.m4a',
  './audio/words/gems.m4a',
  './audio/words/gentle.m4a',
  './audio/words/geode.m4a',
  './audio/words/giant.m4a',
  './audio/words/give.m4a',
  './audio/words/gives.m4a',
  './audio/words/grow.m4a',
  './audio/words/hard.m4a',
  './audio/words/hardest.m4a',
  './audio/words/has.m4a',
  './audio/words/have.m4a',
  './audio/words/heat.m4a',
  './audio/words/heavy.m4a',
  './audio/words/help.m4a',
  './audio/words/home.m4a',
  './audio/words/how.m4a',
  './audio/words/hundred.m4a',
  './audio/words/ice.m4a',
  './audio/words/in.m4a',
  './audio/words/inside.m4a',
  './audio/words/is.m4a',
  './audio/words/it.m4a',
  './audio/words/its.m4a',
  './audio/words/jupiter.m4a',
  './audio/words/light.m4a',
  './audio/words/like.m4a',
  './audio/words/line.m4a',
  './audio/words/lined.m4a',
  './audio/words/litre.m4a',
  './audio/words/litres.m4a',
  './audio/words/living.m4a',
  './audio/words/long.m4a',
  './audio/words/looks.m4a',
  './audio/words/loved.m4a',
  './audio/words/made.m4a',
  './audio/words/many.m4a',
  './audio/words/material.m4a',
  './audio/words/measure.m4a',
  './audio/words/measuring.m4a',
  './audio/words/metre.m4a',
  './audio/words/millimetre.m4a',
  './audio/words/millimetres.m4a',
  './audio/words/mineral.m4a',
  './audio/words/minerals.m4a',
  './audio/words/moon.m4a',
  './audio/words/moons.m4a',
  './audio/words/more.m4a',
  './audio/words/most.m4a',
  './audio/words/much.m4a',
  './audio/words/natural.m4a',
  './audio/words/nature.m4a',
  './audio/words/neat.m4a',
  './audio/words/news.m4a',
  './audio/words/next.m4a',
  './audio/words/not.m4a',
  './audio/words/now.m4a',
  './audio/words/of.m4a',
  './audio/words/on.m4a',
  './audio/words/one.m4a',
  './audio/words/opal.m4a',
  './audio/words/or.m4a',
  './audio/words/other.m4a',
  './audio/words/our.m4a',
  './audio/words/oysters.m4a',
  './audio/words/parts.m4a',
  './audio/words/pattern.m4a',
  './audio/words/pearls.m4a',
  './audio/words/people.m4a',
  './audio/words/picture.m4a',
  './audio/words/pieces.m4a',
  './audio/words/plain.m4a',
  './audio/words/planet.m4a',
  './audio/words/planets.m4a',
  './audio/words/polishes.m4a',
  './audio/words/pressure.m4a',
  './audio/words/purple.m4a',
  './audio/words/quartz.m4a',
  './audio/words/rain.m4a',
  './audio/words/rainbow.m4a',
  './audio/words/rings.m4a',
  './audio/words/rock.m4a',
  './audio/words/rough.m4a',
  './audio/words/rubies.m4a',
  './audio/words/same.m4a',
  './audio/words/sap.m4a',
  './audio/words/sapphires.m4a',
  './audio/words/saturn.m4a',
  './audio/words/says.m4a',
  './audio/words/scale.m4a',
  './audio/words/shall.m4a',
  './audio/words/shapes.m4a',
  './audio/words/short.m4a',
  './audio/words/shower.m4a',
  './audio/words/slow.m4a',
  './audio/words/slowly.m4a',
  './audio/words/solar.m4a',
  './audio/words/some.m4a',
  './audio/words/space.m4a',
  './audio/words/sparkling.m4a',
  './audio/words/square.m4a',
  './audio/words/star.m4a',
  './audio/words/stations.m4a',
  './audio/words/stone.m4a',
  './audio/words/storms.m4a',
  './audio/words/sun.m4a',
  './audio/words/system.m4a',
  './audio/words/tells.m4a',
  './audio/words/ten.m4a',
  './audio/words/thailand.m4a',
  './audio/words/that.m4a',
  './audio/words/the.m4a',
  './audio/words/them.m4a',
  './audio/words/then.m4a',
  './audio/words/they.m4a',
  './audio/words/things.m4a',
  './audio/words/through.m4a',
  './audio/words/time.m4a',
  './audio/words/tiny.m4a',
  './audio/words/total.m4a',
  './audio/words/travels.m4a',
  './audio/words/tree.m4a',
  './audio/words/trip.m4a',
  './audio/words/turned.m4a',
  './audio/words/underground.m4a',
  './audio/words/up.m4a',
  './audio/words/us.m4a',
  './audio/words/very.m4a',
  './audio/words/water.m4a',
  './audio/words/we.m4a',
  './audio/words/weather.m4a',
  './audio/words/what.m4a',
  './audio/words/when.m4a',
  './audio/words/with.m4a',
  './audio/words/world.m4a',
  './books/gems/art/amethyst.webp',
  './books/gems/art/back-home.webp',
  './books/gems/art/cover.webp',
  './books/gems/art/crystals.webp',
  './books/gems/art/cutting.webp',
  './books/gems/art/diamond.webp',
  './books/gems/art/geode.webp',
  './books/gems/art/minerals.webp',
  './books/gems/art/opal.webp',
  './books/gems/art/pearl-amber.webp',
  './books/gems/art/ruby-sapphire.webp',
  './books/gems/art/underground.webp',
  './books/gems/art/what-is-a-gem.webp',
  './books/gems/book.json',
  './books/how-much-rain/art/accumulated.webp',
  './books/how-much-rain/art/closing.webp',
  './books/how-much-rain/art/cover.webp',
  './books/how-much-rain/art/measuring-network.webp',
  './books/how-much-rain/art/news-numbers.webp',
  './books/how-much-rain/art/one-millimetre.webp',
  './books/how-much-rain/art/rain-gauge.webp',
  './books/how-much-rain/art/rain-intensity.webp',
  './books/how-much-rain/art/short-vs-long.webp',
  './books/how-much-rain/art/ten-millimetres.webp',
  './books/how-much-rain/book.json',
  './books/index.json',
  './books/space-trip/art/back-home.webp',
  './books/space-trip/art/contact.webp',
  './books/space-trip/art/cover.webp',
  './books/space-trip/art/earth-moon.webp',
  './books/space-trip/art/jupiter.webp',
  './books/space-trip/art/saturn.webp',
  './books/space-trip/art/solar-system.webp',
  './books/space-trip/art/sun.webp',
  './books/space-trip/book.json',
  './books/where-rain-goes/art/canals-to-river.webp',
  './books/where-rain-goes/art/closing.webp',
  './books/where-rain-goes/art/cover.webp',
  './books/where-rain-goes/art/drains.webp',
  './books/where-rain-goes/art/full-sponge.webp',
  './books/where-rain-goes/art/one-journey-map.webp',
  './books/where-rain-goes/art/rain-lands.webp',
  './books/where-rain-goes/art/runoff.webp',
  './books/where-rain-goes/art/soil-sponge.webp',
  './books/where-rain-goes/art/storage.webp',
  './books/where-rain-goes/art/sun-takes-water.webp',
  './books/where-rain-goes/book.json',
  './index.html',
  './reader/fonts/FredokaOne-latin.woff2',
  './reader/fonts/Nunito-latin.woff2',
  './reader/index.html',
  './reader/js/tap-zoom-guard.js',
  './reader/reader.css',
  './reader/reader.js',
  './shelf/bg-landscape.webp',
  './shelf/bg-portrait.webp',
  './shelf/icon-bookshelf.webp',
  './shelf/shelf.css',
  './shelf/shelf.js',
  './shelf/tap-zoom-guard.js',
  './audio/words/again.m4a',
  './audio/words/always.m4a',
  './audio/words/another.m4a',
  './audio/words/as.m4a',
  './audio/words/back.m4a',
  './audio/words/boats.m4a',
  './audio/words/canals.m4a',
  './audio/words/carry.m4a',
  './audio/words/day.m4a',
  './audio/words/days.m4a',
  './audio/words/does.m4a',
  './audio/words/downhill.m4a',
  './audio/words/drains.m4a',
  './audio/words/drinks.m4a',
  './audio/words/drop.m4a',
  './audio/words/dry.m4a',
  './audio/words/each.m4a',
  './audio/words/extra.m4a',
  './audio/words/faster.m4a',
  './audio/words/fill.m4a',
  './audio/words/flows.m4a',
  './audio/words/follow.m4a',
  './audio/words/full.m4a',
  './audio/words/go.m4a',
  './audio/words/goes.m4a',
  './audio/words/grass.m4a',
  './audio/words/ground.m4a',
  './audio/words/into.m4a',
  './audio/words/journey.m4a',
  './audio/words/journeys.m4a',
  './audio/words/keep.m4a',
  './audio/words/landing.m4a',
  './audio/words/lands.m4a',
  './audio/words/lead.m4a',
  './audio/words/leaves.m4a',
  './audio/words/lifts.m4a',
  './audio/words/lower.m4a',
  './audio/words/paper.m4a',
  './audio/words/places.m4a',
  './audio/words/ponds.m4a',
  './audio/words/puddles.m4a',
  './audio/words/rains.m4a',
  './audio/words/reservoirs.m4a',
  './audio/words/rivers.m4a',
  './audio/words/roads.m4a',
  './audio/words/roofs.m4a',
  './audio/words/sea.m4a',
  './audio/words/slides.m4a',
  './audio/words/slips.m4a',
  './audio/words/soil.m4a',
  './audio/words/sponge.m4a',
  './audio/words/start.m4a',
  './audio/words/stays.m4a',
  './audio/words/stored.m4a',
  './audio/words/street.m4a',
  './audio/words/take.m4a',
  './audio/words/takes.m4a',
  './audio/words/tanks.m4a',
  './audio/words/than.m4a',
  './audio/words/these.m4a',
  './audio/words/to.m4a',
  './audio/words/top.m4a',
  './audio/words/towns.m4a',
  './audio/words/under.m4a',
  './audio/words/vapour.m4a',
  './audio/words/waits.m4a',
  './audio/words/watch.m4a',
  './audio/words/where.m4a',
  './audio/words/favourite.m4a',
  './audio/words/goodnight.m4a',
  './audio/words/own.m4a',
  './audio/words/read.m4a',
  './audio/words/shining.m4a',
  './audio/words/sparkle.m4a',
  './audio/words/stars.m4a',
  './audio/words/which.m4a',
  './audio/words/your.m4a',
];
self.addEventListener('install', event => event.waitUntil(
  caches.open(CACHE_NAME).then(cache => cache.addAll(SHELL)).then(() => self.skipWaiting())));
self.addEventListener('activate', event => event.waitUntil(
  caches.keys().then(keys => Promise.all(keys
    .filter(key => key.startsWith(CACHE_PREFIX) && key !== CACHE_NAME)
    .map(key => caches.delete(key)))).then(() => self.clients.claim())));
self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  event.respondWith(
    caches.open(CACHE_NAME).then(cache => cache.match(req, { ignoreSearch: req.mode === 'navigate' }))
      .then(hit => hit || fetch(req).then(response => {
        if (response && response.status === 200 && response.type === 'basic') {
          const copy = response.clone();
          caches.open(CACHE_NAME).then(cache => cache.put(req, copy));
        }
        return response;
      })));
});
