import {GameState} from './game-state.js';
import {QueueEngine} from './queue-engine.js';
import {RulesEngine} from './rules-engine.js';
import {ShopEngine} from './shop-engine.js';
import {CPUPlayer} from './cpu-player.js';
import {Renderer} from './renderer.js';
import {BalanceConfig as C} from './balance-config.js';

export class Sound {
  constructor(host=window){this.host=host;this.on=true;this.music=false;this.unlocked=false;this.musicTimer=null;this.nextBeat=0;this.beat=0}
  installUnlock(target=document){const unlock=()=>this.unlock();for(const type of ['pointerdown','touchend','click'])target.addEventListener(type,unlock,{capture:true,passive:true,once:true});target.addEventListener('visibilitychange',()=>{if(target.visibilityState==='visible'&&this.c)this.c.resume().then(()=>{if(this.music)this.startMusic()}).catch(()=>{});else if(target.visibilityState==='hidden')this.stopMusic()})}
  context(){if(this.c)return this.c;const A=this.host.AudioContext||this.host.webkitAudioContext;if(!A)return null;const c=this.c=new A,master=this.master=c.createGain(),compressor=this.compressor=c.createDynamicsCompressor(),musicBus=this.musicBus=c.createGain();master.gain.setValueAtTime(.35,c.currentTime);compressor.threshold.setValueAtTime(-18,c.currentTime);compressor.knee.setValueAtTime(12,c.currentTime);compressor.ratio.setValueAtTime(5,c.currentTime);compressor.attack.setValueAtTime(.003,c.currentTime);compressor.release.setValueAtTime(.18,c.currentTime);musicBus.gain.setValueAtTime(.9,c.currentTime);master.connect(compressor).connect(c.destination);musicBus.connect(master);return c}
  unlock(){try{navigator.audioSession.type='playback'}catch{}const c=this.context();if(!c)return Promise.resolve(false);const finish=()=>{if(c.state!=='running')return false;if(!this.unlocked){const b=c.createBuffer(1,1,c.sampleRate),s=c.createBufferSource();s.buffer=b;s.connect(this.master);s.start(0);this.unlocked=true;this.music=true;this.onChange?.()}if(this.music)this.startMusic();return true};return c.state==='running'?Promise.resolve(finish()):c.resume().then(finish).catch(()=>false)}
  setMusic(on){this.music=on;if(on&&this.unlocked)this.startMusic();else this.stopMusic()}
  _gain(at,volume,duration,dest=this.master){const g=this.c.createGain();g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(volume,at+.008);g.gain.exponentialRampToValueAtTime(.0001,at+duration);g.connect(dest);return g}
  _tone(freq,at,duration,volume=.42,type='sine',end=freq,dest=this.master){const o=this.c.createOscillator(),g=this._gain(at,volume,duration,dest);o.type=type;o.frequency.setValueAtTime(freq,at);if(end!==freq)o.frequency.exponentialRampToValueAtTime(end,at+duration*.75);o.connect(g);o.start(at);o.stop(at+duration+.02)}
  _noise(at,duration,volume=.28){const frames=Math.max(1,Math.floor(this.c.sampleRate*duration)),b=this.c.createBuffer(1,frames,this.c.sampleRate),data=b.getChannelData(0);for(let i=0;i<frames;i++)data[i]=(Math.random()*2-1)*(1-i/frames);const s=this.c.createBufferSource(),g=this._gain(at,volume,duration);s.buffer=b;s.connect(g);s.start(at);s.stop(at+duration+.02)}
  play(kind,detail={}){if(!this.on)return;const c=this.context();if(!c)return;const run=()=>{if(c.state!=='running')return;const t=c.currentTime+.006,size=Math.max(3,detail.size||3),lift=1+Math.min(5,size-3)*.08;if(kind==='place'){this._tone(300,t,.12,.38,'triangle',430);this._tone(720,t+.035,.07,.16,'sine',600)}else if(kind==='merge'){this._tone(480*lift,t,.18,.42,'triangle',560*lift);this._tone(720*lift,t+.09,.24,.46,'sine',880*lift)}else if(kind==='jackpot'){[784,988,1175,1568].forEach((f,i)=>this._tone(f,t+i*.065,.22,.32,'sine',f*1.04))}else if(kind==='waste'){this._tone(145,t,.22,.42,'triangle',92);this._noise(t,.11,.10)}else if(kind==='bomb'){this._tone(105,t,.42,.62,'sine',48);this._noise(t,.25,.36)}else if(kind==='buy'){this._tone(880,t,.10,.36,'square',1100);this._tone(1320,t+.065,.13,.30,'sine',1500)}else if(kind==='invalid'){this._tone(175,t,.18,.25,'triangle',135)}else if(kind==='cleanup'){[440,660,880].forEach((f,i)=>this._tone(f,t+i*.045,.16,.27,'sine',f*1.1))}else if(kind==='wildcard'){[520,780,1040].forEach((f,i)=>this._tone(f,t+i*.04,.20,.28,'triangle',f*1.18))}else if(kind==='hand'){this._tone(420,t,.15,.34,'triangle',640);this._tone(520,t+.07,.14,.25,'sine',760)}};if(c.state==='running')run();else c.resume().then(run).catch(()=>{})}
  startMusic(){if(!this.music||!this.unlocked||!this.c||this.c.state!=='running'||this.musicTimer)return;this.nextBeat=this.c.currentTime+.05;this.beat=0;this.scheduleMusic();this.musicTimer=this.host.setInterval(()=>this.scheduleMusic(),100)}
  stopMusic(){if(this.musicTimer){this.host.clearInterval(this.musicTimer);this.musicTimer=null}if(this.musicBus&&this.c){this.musicBus.gain.cancelScheduledValues(this.c.currentTime);this.musicBus.gain.setTargetAtTime(.0001,this.c.currentTime,.025)}}
  scheduleMusic(){if(!this.music||!this.c||this.c.state!=='running')return;this.musicBus.gain.cancelScheduledValues(this.c.currentTime);this.musicBus.gain.setTargetAtTime(.9,this.c.currentTime,.03);const step=60/96/2,notes=[523.25,659.25,783.99,659.25,587.33,698.46,880,698.46,523.25,659.25,783.99,987.77,587.33,698.46,783.99,659.25],bass=[130.81,146.83,130.81,146.83];while(this.nextBeat<this.c.currentTime+.35){const i=this.beat%notes.length;this._tone(notes[i],this.nextBeat,step*.72,.10,'sine',notes[i],this.musicBus);if(i%4===0)this._tone(bass[Math.floor(i/4)],this.nextBeat,step*3.4,.07,'triangle',bass[Math.floor(i/4)]*.995,this.musicBus);this.nextBeat+=step;this.beat++}}
}

export class NumberLabApp {
  constructor(){this.sound=new Sound;this.opponentVisible=false;this.tool=null;this.handFrom=null;this.reset();this.bind();this.sound.onChange=()=>this.render();this.sound.installUnlock(document)}
  reset(mode='solo',profile='QUICK',minutes=10){clearTimeout(this.cpuLoop);clearInterval(this.clock);this.tool=null;this.handFrom=null;this.s=new GameState({seed:Date.now(),mode});this.q=new QueueEngine(this.s);this.r=new RulesEngine(this.s,e=>this.sound.play(e.type==='jackpot'?'jackpot':e.type==='waste-spawn'?'waste':e.cleaned?.length?'cleanup':'merge',e));this.shop=new ShopEngine(this.s,this.q);this.cpu=null;if(mode==='battle'){const cs=new GameState({seed:Date.now()+1337,mode:'battle'});this.cpu=new CPUPlayer(cs,profile);this.timeLeft=minutes*60;const go=()=>{if(!this.cpu||this.timeLeft<=0)return;if(!this.cpu.act())return this.finishBattle('cpu');this.render();this.cpuLoop=setTimeout(go,this.cpu.delay())};go();this.clock=setInterval(()=>{if(--this.timeLeft<=0)this.finishBattle();this.render()},1000)}this.renderer=new Renderer(this);this.render()}
  bind(){document.addEventListener('click',e=>{const cell=e.target.closest('.cell');if(cell)return this.tapCell(+cell.dataset.i);const b=e.target.closest('[data-act]');if(!b)return;const a=b.dataset.act;if(a==='hold'){this.q.hold();this.sound.play('place')}if(a==='tools')document.querySelector('#toolbox').showModal();if(a==='restart')this.reset(this.s.mode);if(a==='opponent')this.opponentVisible=!this.opponentVisible;if(a==='sound')this.sound.on=!this.sound.on;if(a==='music')this.sound.setMusic(!this.sound.music);if(a==='mode')this.reset(b.dataset.mode,b.dataset.profile||'QUICK',+(b.dataset.minutes||10));if(a==='buy'&&this.shop.buy(b.dataset.id))this.sound.play('buy');if(['bomb','hand','wildcard'].includes(a)&&this.s.inventory[a]>0){this.tool=a;document.querySelector('#toolbox').close()}this.render()});document.querySelector('#toolbox').addEventListener('click',e=>{if(e.target===e.currentTarget)e.currentTarget.close()})}
  validWildcard(i){if(this.s.board[i])return false;const counts=new Map;for(const n of this.r.neighbors(i)){const t=this.s.board[n];if(t&&['A','B'].includes(t.family)){const chain=t.family==='A'?C.familyA:C.familyB;if(t.tier!==chain.at(-1)){const k=t.family+t.tier;counts.set(k,(counts.get(k)||0)+1)}}}return [...counts.values()].some(n=>n>=2)}
  tapCell(i){if(this.s.gameOver)return;if(this.tool==='bomb'){if(this.r.bomb(i)){this.s.inventory.bomb--;this.tool=null;this.sound.play('bomb')}else this.sound.play('invalid')}else if(this.tool==='hand'){if(this.handFrom===null&&this.s.board[i])this.handFrom=i;else if(this.handFrom!==null&&!this.s.board[i]){if(this.r.hand(this.handFrom,i).ok){this.s.inventory.hand--;this.sound.play('hand')}else this.sound.play('invalid');this.handFrom=null;this.tool=null}else this.sound.play('invalid')}else if(this.tool==='wildcard'){if(!this.s.board[i]){const candidates=this.r.neighbors(i).map(n=>this.s.board[n]).filter(t=>t&&['A','B'].includes(t.family));let done=false;for(const t of candidates)if(this.r.wildcard(i,t.tier,t.family).ok){this.s.inventory.wildcard--;this.tool=null;this.sound.play('wildcard');done=true;break}if(!done)this.sound.play('invalid')}else this.sound.play('invalid')}else if(!this.s.board[i]){this.r.place(i,this.q.active);this.q.consume();this.sound.play('place')}else{this.sound.play('invalid')}if(!this.r.legal()){this.s.gameOver=true;if(this.s.mode==='battle')this.finishBattle('player');else this.saveRecord()}this.render()}
  saveRecord(){try{const old=JSON.parse(localStorage.getItem('number-lab-records')||'{}');localStorage.setItem('number-lab-records',JSON.stringify({highScore:Math.max(old.highScore||0,this.s.score),highestA:this.s.stats.highestA,jackpots:Math.max(old.jackpots||0,this.s.stats.jackpots),biggestJackpot:Math.max(old.biggestJackpot||0,this.s.stats.biggestJackpot),longestCascade:Math.max(old.longestCascade||0,this.s.stats.longestCascade),largestMerge:Math.max(old.largestMerge||0,this.s.stats.largestMerge),milestones:{...(old.milestones||{}),...this.s.stats.milestones}}))}catch{}}
  finishBattle(unable){if(!this.cpu||this.s.gameOver&&this.cpu.s.gameOver)return;clearTimeout(this.cpuLoop);clearInterval(this.clock);this.s.gameOver=true;this.cpu.s.gameOver=true;const playerWins=unable==='cpu'||(unable!=='player'&&this.s.score>=this.cpu.s.score);document.querySelector('#result-title').textContent=playerWins?'YOU WIN!':'CPU WINS';document.querySelector('#result-scores').textContent=`${this.s.score.toLocaleString()} — ${this.cpu.s.score.toLocaleString()}`;document.querySelector('#result').showModal()}
  render(){this.renderer.draw();document.querySelector('#timer').textContent=this.s.mode==='battle'?`${Math.floor(this.timeLeft/60)}:${String(this.timeLeft%60).padStart(2,'0')}`:'ENDLESS';document.querySelector('#opponent-toggle').hidden=!this.cpu;document.querySelector('#opponent-toggle').textContent=this.opponentVisible?'HIDE OPPONENT':'SHOW OPPONENT';document.querySelector('#status').textContent=this.tool?`${this.tool.toUpperCase()} ACTIVE`:this.s.gameOver?'BOARD FULL — RESTART':'PLACE THE NEXT TILE';document.querySelector('[data-act="sound"]').setAttribute('aria-pressed',String(this.sound.on));document.querySelector('[data-act="music"]').setAttribute('aria-pressed',String(this.sound.music));document.querySelectorAll('[data-id]').forEach(b=>{const id=b.dataset.id;b.disabled=this.s.shopStock[id]<=0||this.s.credits<C.prices[id];const stock=b.querySelector('.stock');if(stock)stock.textContent=`×${this.s.shopStock[id]}`})}
}

if(typeof window!=='undefined'&&typeof document!=='undefined')window.__numberLab=new NumberLabApp;
