import {GameState} from './game-state.js';
import {QueueEngine} from './queue-engine.js';
import {RulesEngine} from './rules-engine.js';
import {ShopEngine} from './shop-engine.js';
import {CPUPlayer} from './cpu-player.js';
import {Renderer} from './renderer.js';
import {BalanceConfig as C} from './balance-config.js';

class Sound {
  constructor(){this.on=true;this.music=false}
  play(kind){if(!this.on)return;const A=window.AudioContext||window.webkitAudioContext;if(!A)return;this.c??=new A;const o=this.c.createOscillator(),g=this.c.createGain(),f={place:360,merge:620,waste:190,jackpot:980,buy:720,bomb:110,hand:510,wildcard:840,cleanup:700,invalid:150}[kind]||440;o.frequency.setValueAtTime(f,this.c.currentTime);o.frequency.exponentialRampToValueAtTime(f*1.45,this.c.currentTime+.1);g.gain.setValueAtTime(.07,this.c.currentTime);g.gain.exponentialRampToValueAtTime(.001,this.c.currentTime+.14);o.connect(g).connect(this.c.destination);o.start();o.stop(this.c.currentTime+.15)}
}

export class NumberLabApp {
  constructor(){this.sound=new Sound;this.opponentVisible=false;this.tool=null;this.handFrom=null;this.reset();this.bind()}
  reset(mode='solo',profile='QUICK',minutes=10){clearTimeout(this.cpuLoop);clearInterval(this.clock);this.tool=null;this.handFrom=null;this.s=new GameState({seed:Date.now(),mode});this.q=new QueueEngine(this.s);this.r=new RulesEngine(this.s,e=>this.sound.play(e.type==='jackpot'?'jackpot':e.type==='waste-spawn'?'waste':e.cleaned?.length?'cleanup':'merge'));this.shop=new ShopEngine(this.s,this.q);this.cpu=null;if(mode==='battle'){const cs=new GameState({seed:Date.now()+1337,mode:'battle'});this.cpu=new CPUPlayer(cs,profile);this.timeLeft=minutes*60;const go=()=>{if(!this.cpu||this.timeLeft<=0)return;if(!this.cpu.act())return this.finishBattle('cpu');this.render();this.cpuLoop=setTimeout(go,this.cpu.delay())};go();this.clock=setInterval(()=>{if(--this.timeLeft<=0)this.finishBattle();this.render()},1000)}this.renderer=new Renderer(this);this.render()}
  bind(){document.addEventListener('click',e=>{const cell=e.target.closest('.cell');if(cell)return this.tapCell(+cell.dataset.i);const b=e.target.closest('[data-act]');if(!b)return;const a=b.dataset.act;if(a==='hold'){this.q.hold();this.sound.play('place')}if(a==='tools')document.querySelector('#toolbox').showModal();if(a==='restart')this.reset(this.s.mode);if(a==='opponent')this.opponentVisible=!this.opponentVisible;if(a==='sound')this.sound.on=!this.sound.on;if(a==='music')this.sound.music=!this.sound.music;if(a==='mode')this.reset(b.dataset.mode,b.dataset.profile||'QUICK',+(b.dataset.minutes||10));if(a==='buy'&&this.shop.buy(b.dataset.id))this.sound.play('buy');if(['bomb','hand','wildcard'].includes(a)&&this.s.inventory[a]>0){this.tool=a;document.querySelector('#toolbox').close()}this.render()});document.querySelector('#toolbox').addEventListener('click',e=>{if(e.target===e.currentTarget)e.currentTarget.close()})}
  validWildcard(i){if(this.s.board[i])return false;const counts=new Map;for(const n of this.r.neighbors(i)){const t=this.s.board[n];if(t&&['A','B'].includes(t.family)){const chain=t.family==='A'?C.familyA:C.familyB;if(t.tier!==chain.at(-1)){const k=t.family+t.tier;counts.set(k,(counts.get(k)||0)+1)}}}return [...counts.values()].some(n=>n>=2)}
  tapCell(i){if(this.s.gameOver)return;if(this.tool==='bomb'){if(this.r.bomb(i)){this.s.inventory.bomb--;this.tool=null;this.sound.play('bomb')}else this.sound.play('invalid')}else if(this.tool==='hand'){if(this.handFrom===null&&this.s.board[i])this.handFrom=i;else if(this.handFrom!==null&&!this.s.board[i]){if(this.r.hand(this.handFrom,i).ok){this.s.inventory.hand--;this.sound.play('hand')}else this.sound.play('invalid');this.handFrom=null;this.tool=null}else this.sound.play('invalid')}else if(this.tool==='wildcard'){if(!this.s.board[i]){const candidates=this.r.neighbors(i).map(n=>this.s.board[n]).filter(t=>t&&['A','B'].includes(t.family));let done=false;for(const t of candidates)if(this.r.wildcard(i,t.tier,t.family).ok){this.s.inventory.wildcard--;this.tool=null;this.sound.play('wildcard');done=true;break}if(!done)this.sound.play('invalid')}else this.sound.play('invalid')}else if(!this.s.board[i]){this.r.place(i,this.q.active);this.q.consume();this.sound.play('place')}else{this.sound.play('invalid')}if(!this.r.legal()){this.s.gameOver=true;if(this.s.mode==='battle')this.finishBattle('player');else this.saveRecord()}this.render()}
  saveRecord(){try{const old=JSON.parse(localStorage.getItem('number-lab-records')||'{}');localStorage.setItem('number-lab-records',JSON.stringify({highScore:Math.max(old.highScore||0,this.s.score),highestA:this.s.stats.highestA,jackpots:Math.max(old.jackpots||0,this.s.stats.jackpots),biggestJackpot:Math.max(old.biggestJackpot||0,this.s.stats.biggestJackpot),longestCascade:Math.max(old.longestCascade||0,this.s.stats.longestCascade),largestMerge:Math.max(old.largestMerge||0,this.s.stats.largestMerge),milestones:{...(old.milestones||{}),...this.s.stats.milestones}}))}catch{}}
  finishBattle(unable){if(!this.cpu||this.s.gameOver&&this.cpu.s.gameOver)return;clearTimeout(this.cpuLoop);clearInterval(this.clock);this.s.gameOver=true;this.cpu.s.gameOver=true;const playerWins=unable==='cpu'||(unable!=='player'&&this.s.score>=this.cpu.s.score);document.querySelector('#result-title').textContent=playerWins?'YOU WIN!':'CPU WINS';document.querySelector('#result-scores').textContent=`${this.s.score.toLocaleString()} — ${this.cpu.s.score.toLocaleString()}`;document.querySelector('#result').showModal()}
  render(){this.renderer.draw();document.querySelector('#timer').textContent=this.s.mode==='battle'?`${Math.floor(this.timeLeft/60)}:${String(this.timeLeft%60).padStart(2,'0')}`:'ENDLESS';document.querySelector('#opponent-toggle').hidden=!this.cpu;document.querySelector('#opponent-toggle').textContent=this.opponentVisible?'HIDE OPPONENT':'SHOW OPPONENT';document.querySelector('#status').textContent=this.tool?`${this.tool.toUpperCase()} ACTIVE`:this.s.gameOver?'BOARD FULL — RESTART':'PLACE THE NEXT TILE';document.querySelector('[data-act="sound"]').setAttribute('aria-pressed',String(this.sound.on));document.querySelector('[data-act="music"]').setAttribute('aria-pressed',String(this.sound.music));document.querySelectorAll('[data-id]').forEach(b=>{const id=b.dataset.id;b.disabled=this.s.shopStock[id]<=0||this.s.credits<C.prices[id];const stock=b.querySelector('.stock');if(stock)stock.textContent=`×${this.s.shopStock[id]}`})}
}

window.__numberLab=new NumberLabApp;
