// Generated by music-book/tools/stage-title-sentences-testhub.sh. Do not edit.
window.LISTEN_CLIPS = [
{
"id": "ode-to-joy",
"file": "ode-to-joy.m4a",
"class": "classical",
"sentence": "This music is called Ode to Joy."
},
{
"id": "fur-elise",
"file": "fur-elise.m4a",
"class": "classical",
"sentence": "This music is called Für Elise."
},
{
"id": "moonlight-sonata",
"file": "moonlight-sonata.m4a",
"class": "classical",
"sentence": "This music is called Moonlight Sonata."
},
{
"id": "symphony-5-opening",
"file": "symphony-5-opening.m4a",
"class": "classical",
"sentence": "This music is called Symphony Number Five, the opening."
},
{
"id": "twinkle",
"file": "twinkle.m4a",
"class": "song",
"sentence": "This song is called Twinkle Twinkle Little Star."
},
{
"id": "swan-lake-theme",
"file": "swan-lake-theme.m4a",
"class": "classical",
"sentence": "This music is called Swan Lake, the theme."
},
{
"id": "mary-had-little-lamb",
"file": "mary-had-little-lamb.m4a",
"class": "song",
"sentence": "This song is called Mary Had a Little Lamb."
},
{
"id": "frere-jacques",
"file": "frere-jacques.m4a",
"class": "song",
"sentence": "This song is called Frère Jacques."
},
{
"id": "row-row-row-your-boat",
"file": "row-row-row-your-boat.m4a",
"class": "song",
"sentence": "This song is called Row, Row, Row Your Boat."
},
{
"id": "old-macdonald",
"file": "old-macdonald.m4a",
"class": "song",
"sentence": "This song is called Old MacDonald Had a Farm."
},
{
"id": "bingo",
"file": "bingo.m4a",
"class": "song",
"sentence": "This song is called BINGO."
},
{
"id": "london-bridge",
"file": "london-bridge.m4a",
"class": "song",
"sentence": "This song is called London Bridge Is Falling Down."
},
{
"id": "pop-goes-weasel",
"file": "pop-goes-weasel.m4a",
"class": "song",
"sentence": "This song is called Pop Goes the Weasel."
},
{
"id": "three-blind-mice",
"file": "three-blind-mice.m4a",
"class": "song",
"sentence": "This song is called Three Blind Mice."
},
{
"id": "hot-cross-buns",
"file": "hot-cross-buns.m4a",
"class": "song",
"sentence": "This song is called Hot Cross Buns."
},
{
"id": "this-old-man",
"file": "this-old-man.m4a",
"class": "song",
"sentence": "This song is called This Old Man."
},
{
"id": "farmer-in-dell",
"file": "farmer-in-dell.m4a",
"class": "song",
"sentence": "This song is called The Farmer in the Dell."
},
{
"id": "mulberry-bush",
"file": "mulberry-bush.m4a",
"class": "song",
"sentence": "This song is called Here We Go Round the Mulberry Bush."
},
{
"id": "rock-a-bye-baby",
"file": "rock-a-bye-baby.m4a",
"class": "song",
"sentence": "This song is called Rock-a-bye Baby."
},
{
"id": "skip-to-my-lou",
"file": "skip-to-my-lou.m4a",
"class": "song",
"sentence": "This song is called Skip to My Lou."
},
{
"id": "amazing-grace-new-britain",
"file": "amazing-grace-new-britain.m4a",
"class": "song",
"sentence": "This song is called Amazing Grace."
},
{
"id": "when-saints-go-marching",
"file": "when-saints-go-marching.m4a",
"class": "song",
"sentence": "This song is called When the Saints Go Marching In."
},
{
"id": "simple-gifts",
"file": "simple-gifts.m4a",
"class": "song",
"sentence": "This song is called Simple Gifts."
},
{
"id": "my-bonnie",
"file": "my-bonnie.m4a",
"class": "song",
"sentence": "This song is called My Bonnie Lies over the Ocean."
},
{
"id": "home-on-range",
"file": "home-on-range.m4a",
"class": "song",
"sentence": "This song is called Home on the Range."
},
{
"id": "happy-birthday",
"file": "happy-birthday.m4a",
"class": "song",
"sentence": "This song is called Happy Birthday to You."
},
{
"id": "jolly-good-fellow",
"file": "jolly-good-fellow.m4a",
"class": "song",
"sentence": "This song is called For He's a Jolly Good Fellow."
},
{
"id": "jingle-bells",
"file": "jingle-bells.m4a",
"class": "song",
"sentence": "This song is called Jingle Bells.",
"gainTrimDb": 2.0
},
{
"id": "silent-night",
"file": "silent-night.m4a",
"class": "song",
"sentence": "This song is called Silent Night."
},
{
"id": "o-tannenbaum",
"file": "o-tannenbaum.m4a",
"class": "song",
"sentence": "This song is called O Tannenbaum."
},
{
"id": "deck-the-hall",
"file": "deck-the-hall.m4a",
"class": "song",
"sentence": "This song is called Deck the Hall."
},
{
"id": "we-wish-merry-christmas",
"file": "we-wish-merry-christmas.m4a",
"class": "song",
"sentence": "This song is called We Wish You a Merry Christmas."
},
{
"id": "first-noel",
"file": "first-noel.m4a",
"class": "song",
"sentence": "This song is called The First Noel."
},
{
"id": "joy-to-world",
"file": "joy-to-world.m4a",
"class": "song",
"sentence": "This song is called Joy to the World."
},
{
"id": "auld-lang-syne",
"file": "auld-lang-syne.m4a",
"class": "song",
"sentence": "This song is called Auld Lang Syne."
},
{
"id": "sakura-sakura",
"file": "sakura-sakura.m4a",
"class": "song",
"sentence": "This song is called Sakura Sakura."
},
{
"id": "arirang",
"file": "arirang.m4a",
"class": "song",
"sentence": "This song is called Arirang."
},
{
"id": "mo-li-hua",
"file": "mo-li-hua.m4a",
"class": "song",
"sentence": "This song is called Mo Li Hua."
},
{
"id": "rasa-sayang",
"file": "rasa-sayang.m4a",
"class": "song",
"sentence": "This song is called Rasa Sayang."
},
{
"id": "burung-kakak-tua",
"file": "burung-kakak-tua.m4a",
"class": "song",
"sentence": "This song is called Burung Kakak Tua."
},
{
"id": "leron-leron-sinta",
"file": "leron-leron-sinta.m4a",
"class": "song",
"sentence": "This song is called Leron, Leron Sinta."
},
{
"id": "lao-duang-duen",
"file": "lao-duang-duen.m4a",
"class": "song",
"sentence": "This song is called Lao Duang Duen."
},
{
"id": "raghupati-raghava",
"file": "raghupati-raghava.m4a",
"class": "song",
"sentence": "This song is called Raghupati Raghava Raja Ram."
},
{
"id": "uskudara-gider-iken",
"file": "uskudara-gider-iken.m4a",
"class": "song",
"sentence": "This song is called Üsküdar'a Gider İken."
},
{
"id": "hava-nagila",
"file": "hava-nagila.m4a",
"class": "song",
"sentence": "This song is called Hava Nagila."
},
{
"id": "kalinka",
"file": "kalinka.m4a",
"class": "song",
"sentence": "This song is called Kalinka."
},
{
"id": "shchedryk",
"file": "shchedryk.m4a",
"class": "song",
"sentence": "This song is called Shchedryk."
},
{
"id": "nkosi-sikelel-iafrika",
"file": "nkosi-sikelel-iafrika.m4a",
"class": "song",
"sentence": "This song is called Nkosi Sikelel' iAfrika."
},
{
"id": "misirlou",
"file": "misirlou.m4a",
"class": "song",
"sentence": "This song is called Misirlou."
},
{
"id": "waltzing-matilda",
"file": "waltzing-matilda.m4a",
"class": "song",
"sentence": "This song is called Waltzing Matilda."
},
{
"id": "el-condor-pasa",
"file": "el-condor-pasa.m4a",
"class": "song",
"sentence": "This song is called El Cóndor Pasa."
},
{
"id": "la-bamba",
"file": "la-bamba.m4a",
"class": "song",
"sentence": "This song is called La Bamba."
},
{
"id": "greensleeves",
"file": "greensleeves.m4a",
"class": "song",
"sentence": "This song is called Greensleeves."
},
{
"id": "bach-prelude-c-major-bwv-846",
"file": "bach-prelude-c-major-bwv-846.m4a",
"class": "classical",
"sentence": "This music is called Prelude in C major, BWV 846."
},
{
"id": "bach-air-orchestral-suite-3",
"file": "bach-air-orchestral-suite-3.m4a",
"class": "classical",
"sentence": "This music is called Air from Orchestral Suite No. 3."
},
{
"id": "bach-jesu-joy",
"file": "bach-jesu-joy.m4a",
"class": "classical",
"sentence": "This music is called Jesu, Joy of Man's Desiring."
},
{
"id": "bach-cello-suite-1-prelude",
"file": "bach-cello-suite-1-prelude.m4a",
"class": "classical",
"sentence": "This music is called Cello Suite No. 1 — Prelude."
},
{
"id": "vivaldi-spring-1",
"file": "vivaldi-spring-1.m4a",
"class": "classical",
"sentence": "This music is called The Four Seasons — Spring."
},
{
"id": "vivaldi-summer-storm",
"file": "vivaldi-summer-storm.m4a",
"class": "classical",
"sentence": "This music is called The Four Seasons — Summer Storm."
},
{
"id": "vivaldi-winter-1",
"file": "vivaldi-winter-1.m4a",
"class": "classical",
"sentence": "This music is called The Four Seasons — Winter."
},
{
"id": "handel-hallelujah-chorus",
"file": "handel-hallelujah-chorus.m4a",
"class": "classical",
"sentence": "This music is called Messiah — Hallelujah Chorus."
},
{
"id": "handel-water-music-hornpipe",
"file": "handel-water-music-hornpipe.m4a",
"class": "classical",
"sentence": "This music is called Water Music — Hornpipe."
},
{
"id": "handel-royal-fireworks-rejouissance",
"file": "handel-royal-fireworks-rejouissance.m4a",
"class": "classical",
"sentence": "This music is called Music for the Royal Fireworks — La Réjouissance."
},
{
"id": "pachelbel-canon-d",
"file": "pachelbel-canon-d.m4a",
"class": "classical",
"sentence": "This music is called Canon in D."
},
{
"id": "haydn-surprise-symphony-94-2",
"file": "haydn-surprise-symphony-94-2.m4a",
"class": "classical",
"sentence": "This music is called Symphony No. 94 — Surprise."
},
{
"id": "haydn-trumpet-concerto-3",
"file": "haydn-trumpet-concerto-3.m4a",
"class": "classical",
"sentence": "This music is called Trumpet Concerto — third movement."
},
{
"id": "mozart-eine-kleine-nachtmusik-1",
"file": "mozart-eine-kleine-nachtmusik-1.m4a",
"class": "classical",
"sentence": "This music is called Eine kleine Nachtmusik.",
"gainTrimDb": -4.7
},
{
"id": "mozart-rondo-alla-turca",
"file": "mozart-rondo-alla-turca.m4a",
"class": "classical",
"sentence": "This music is called Rondo alla Turca."
},
{
"id": "mozart-symphony-40-1",
"file": "mozart-symphony-40-1.m4a",
"class": "classical",
"sentence": "This music is called Symphony No. 40."
},
{
"id": "mozart-piano-sonata-k545-1",
"file": "mozart-piano-sonata-k545-1.m4a",
"class": "classical",
"sentence": "This music is called Piano Sonata in C, K.545."
},
{
"id": "mozart-ah-vous-dirai-je-variations",
"file": "mozart-ah-vous-dirai-je-variations.m4a",
"class": "classical",
"sentence": "This music is called Twelve Variations on 'Ah! vous dirai-je, maman'."
},
{
"id": "beethoven-symphony-7-2",
"file": "beethoven-symphony-7-2.m4a",
"class": "classical",
"sentence": "This music is called Symphony No. 7 — second movement."
},
{
"id": "schubert-ave-maria",
"file": "schubert-ave-maria.m4a",
"class": "classical",
"sentence": "This music is called Ave Maria."
},
{
"id": "schubert-die-forelle",
"file": "schubert-die-forelle.m4a",
"class": "classical",
"sentence": "This music is called The Trout."
},
{
"id": "mendelssohn-wedding-march",
"file": "mendelssohn-wedding-march.m4a",
"class": "classical",
"sentence": "This music is called Wedding March."
},
{
"id": "mendelssohn-spring-song",
"file": "mendelssohn-spring-song.m4a",
"class": "classical",
"sentence": "This music is called Spring Song."
},
{
"id": "mendelssohn-violin-concerto-opening",
"file": "mendelssohn-violin-concerto-opening.m4a",
"class": "classical",
"sentence": "This music is called Violin Concerto — opening."
},
{
"id": "chopin-nocturne-op9-no2",
"file": "chopin-nocturne-op9-no2.m4a",
"class": "classical",
"sentence": "This music is called Nocturne in E-flat, Opus Nine Number Two.",
"take": 2
},
{
"id": "chopin-minute-waltz",
"file": "chopin-minute-waltz.m4a",
"class": "classical",
"sentence": "This music is called Minute Waltz."
},
{
"id": "chopin-raindrop-prelude",
"file": "chopin-raindrop-prelude.m4a",
"class": "classical",
"sentence": "This music is called Raindrop Prelude."
},
{
"id": "chopin-fantaisie-impromptu",
"file": "chopin-fantaisie-impromptu.m4a",
"class": "classical",
"sentence": "This music is called Fantaisie-Impromptu."
},
{
"id": "schumann-traumerei",
"file": "schumann-traumerei.m4a",
"class": "classical",
"sentence": "This music is called Träumerei."
},
{
"id": "schumann-happy-farmer",
"file": "schumann-happy-farmer.m4a",
"class": "classical",
"sentence": "This music is called The Happy Farmer."
},
{
"id": "schumann-foreign-lands-people",
"file": "schumann-foreign-lands-people.m4a",
"class": "classical",
"sentence": "This music is called Of Foreign Lands and People."
},
{
"id": "brahms-lullaby",
"file": "brahms-lullaby.m4a",
"class": "classical",
"sentence": "This music is called Brahms's Lullaby."
},
{
"id": "brahms-hungarian-dance-5",
"file": "brahms-hungarian-dance-5.m4a",
"class": "classical",
"sentence": "This music is called Hungarian Dance No. 5."
},
{
"id": "brahms-waltz-op39-no15",
"file": "brahms-waltz-op39-no15.m4a",
"class": "classical",
"sentence": "This music is called Waltz in A-flat, Opus Thirty-Nine Number Fifteen.",
"take": 2
},
{
"id": "tchaikovsky-sugar-plum-fairy",
"file": "tchaikovsky-sugar-plum-fairy.m4a",
"class": "classical",
"sentence": "This music is called Dance of the Sugar Plum Fairy."
},
{
"id": "tchaikovsky-waltz-flowers",
"file": "tchaikovsky-waltz-flowers.m4a",
"class": "classical",
"sentence": "This music is called Waltz of the Flowers."
},
{
"id": "tchaikovsky-nutcracker-march",
"file": "tchaikovsky-nutcracker-march.m4a",
"class": "classical",
"sentence": "This music is called The Nutcracker — March."
},
{
"id": "tchaikovsky-trepak",
"file": "tchaikovsky-trepak.m4a",
"class": "classical",
"sentence": "This music is called Russian Dance (Trepak)."
},
{
"id": "tchaikovsky-piano-concerto-1-opening",
"file": "tchaikovsky-piano-concerto-1-opening.m4a",
"class": "classical",
"sentence": "This music is called Piano Concerto No. 1 — opening."
},
{
"id": "saint-saens-the-swan",
"file": "saint-saens-the-swan.m4a",
"class": "classical",
"sentence": "This music is called The Swan."
},
{
"id": "saint-saens-aquarium",
"file": "saint-saens-aquarium.m4a",
"class": "classical",
"sentence": "This music is called Aquarium."
},
{
"id": "saint-saens-danse-macabre",
"file": "saint-saens-danse-macabre.m4a",
"class": "classical",
"sentence": "This music is called Danse macabre."
},
{
"id": "grieg-morning-mood",
"file": "grieg-morning-mood.m4a",
"class": "classical",
"sentence": "This music is called Morning Mood."
},
{
"id": "grieg-mountain-king",
"file": "grieg-mountain-king.m4a",
"class": "classical",
"sentence": "This music is called In the Hall of the Mountain King."
},
{
"id": "grieg-anitras-dance",
"file": "grieg-anitras-dance.m4a",
"class": "classical",
"sentence": "This music is called Anitra's Dance."
},
{
"id": "dvorak-new-world-largo",
"file": "dvorak-new-world-largo.m4a",
"class": "classical",
"sentence": "This music is called Symphony No. 9 — Largo."
},
{
"id": "dvorak-humoresque-7",
"file": "dvorak-humoresque-7.m4a",
"class": "classical",
"sentence": "This music is called Humoresque No. 7."
},
{
"id": "dvorak-slavonic-dance-8",
"file": "dvorak-slavonic-dance-8.m4a",
"class": "classical",
"sentence": "This music is called Slavonic Dance No. 8."
},
{
"id": "mussorgsky-promenade",
"file": "mussorgsky-promenade.m4a",
"class": "classical",
"sentence": "This music is called Pictures at an Exhibition — Promenade."
},
{
"id": "mussorgsky-unhatched-chicks",
"file": "mussorgsky-unhatched-chicks.m4a",
"class": "classical",
"sentence": "This music is called Ballet of the Unhatched Chicks."
},
{
"id": "mussorgsky-night-bald-mountain",
"file": "mussorgsky-night-bald-mountain.m4a",
"class": "classical",
"sentence": "This music is called Night on Bald Mountain."
},
{
"id": "rimsky-flight-bumblebee",
"file": "rimsky-flight-bumblebee.m4a",
"class": "classical",
"sentence": "This music is called Flight of the Bumblebee.",
"gainTrimDb": -3.3
},
{
"id": "rimsky-scheherazade-opening",
"file": "rimsky-scheherazade-opening.m4a",
"class": "classical",
"sentence": "This music is called Scheherazade — opening."
},
{
"id": "strauss-blue-danube",
"file": "strauss-blue-danube.m4a",
"class": "classical",
"sentence": "This music is called The Blue Danube."
},
{
"id": "strauss-tritsch-tratsch-polka",
"file": "strauss-tritsch-tratsch-polka.m4a",
"class": "classical",
"sentence": "This music is called Tritsch-Tratsch-Polka."
},
{
"id": "bizet-habanera",
"file": "bizet-habanera.m4a",
"class": "classical",
"sentence": "This music is called Carmen — Habanera."
},
{
"id": "bizet-toreador-song",
"file": "bizet-toreador-song.m4a",
"class": "classical",
"sentence": "This music is called Carmen — Toreador Song."
},
{
"id": "rossini-william-tell-finale",
"file": "rossini-william-tell-finale.m4a",
"class": "classical",
"sentence": "This music is called William Tell Overture — finale."
},
{
"id": "rossini-barber-seville-overture",
"file": "rossini-barber-seville-overture.m4a",
"class": "classical",
"sentence": "This music is called The Barber of Seville — overture."
},
{
"id": "debussy-clair-de-lune",
"file": "debussy-clair-de-lune.m4a",
"class": "classical",
"sentence": "This music is called Clair de lune."
},
{
"id": "debussy-arabesque-1",
"file": "debussy-arabesque-1.m4a",
"class": "classical",
"sentence": "This music is called Arabesque No. 1."
},
{
"id": "debussy-little-shepherd",
"file": "debussy-little-shepherd.m4a",
"class": "classical",
"sentence": "This music is called The Little Shepherd."
},
{
"id": "satie-gymnopedie-1",
"file": "satie-gymnopedie-1.m4a",
"class": "classical",
"sentence": "This music is called Gymnopédie No. 1."
},
{
"id": "joplin-entertainer",
"file": "joplin-entertainer.m4a",
"class": "classical",
"sentence": "This music is called The Entertainer."
},
{
"id": "joplin-maple-leaf-rag",
"file": "joplin-maple-leaf-rag.m4a",
"class": "classical",
"sentence": "This music is called Maple Leaf Rag."
},
{
"id": "holst-jupiter",
"file": "holst-jupiter.m4a",
"class": "classical",
"sentence": "This music is called The Planets — Jupiter."
},
{
"id": "holst-mars",
"file": "holst-mars.m4a",
"class": "classical",
"sentence": "This music is called The Planets — Mars."
},
{
"id": "composer-beethoven",
"file": "composer-beethoven.m4a",
"class": "composer",
"sentence": "This composer is called Ludwig van Beethoven.",
"take": 2
},
{
"id": "composer-mozart",
"file": "composer-mozart.m4a",
"class": "composer",
"sentence": "This composer is called Wolfgang Amadeus Mozart.",
"take": 2
},
{
"id": "composer-tchaikovsky",
"file": "composer-tchaikovsky.m4a",
"class": "composer",
"sentence": "This composer is called Pyotr Ilyich Tchaikovsky.",
"take": 2
},
{
"id": "composer-traditional",
"file": "composer-traditional.m4a",
"class": "composer",
"sentence": "These are traditional songs.",
"take": 2
},
{
"id": "composer-bach",
"file": "composer-bach.m4a",
"class": "composer",
"sentence": "This composer is called Johann Sebastian Bach.",
"take": 2
},
{
"id": "composer-vivaldi",
"file": "composer-vivaldi.m4a",
"class": "composer",
"sentence": "This composer is called Antonio Vivaldi.",
"take": 2
},
{
"id": "composer-handel",
"file": "composer-handel.m4a",
"class": "composer",
"sentence": "This composer is called George Frideric Handel.",
"take": 2
},
{
"id": "composer-pachelbel",
"file": "composer-pachelbel.m4a",
"class": "composer",
"sentence": "This composer is called Johann Pachelbel.",
"take": 2
},
{
"id": "composer-haydn",
"file": "composer-haydn.m4a",
"class": "composer",
"sentence": "This composer is called Joseph Haydn.",
"take": 2
},
{
"id": "composer-schubert",
"file": "composer-schubert.m4a",
"class": "composer",
"sentence": "This composer is called Franz Schubert.",
"take": 2
},
{
"id": "composer-mendelssohn",
"file": "composer-mendelssohn.m4a",
"class": "composer",
"sentence": "This composer is called Felix Mendelssohn.",
"take": 2
},
{
"id": "composer-chopin",
"file": "composer-chopin.m4a",
"class": "composer",
"sentence": "This composer is called Frédéric Chopin.",
"take": 2
},
{
"id": "composer-schumann",
"file": "composer-schumann.m4a",
"class": "composer",
"sentence": "This composer is called Robert Schumann.",
"take": 2
},
{
"id": "composer-brahms",
"file": "composer-brahms.m4a",
"class": "composer",
"sentence": "This composer is called Johannes Brahms.",
"take": 2
},
{
"id": "composer-saint-saens",
"file": "composer-saint-saens.m4a",
"class": "composer",
"sentence": "This composer is called Camille Saint-Saëns.",
"take": 2
},
{
"id": "composer-grieg",
"file": "composer-grieg.m4a",
"class": "composer",
"sentence": "This composer is called Edvard Grieg.",
"take": 2
},
{
"id": "composer-dvorak",
"file": "composer-dvorak.m4a",
"class": "composer",
"sentence": "This composer is called Antonín Dvořák.",
"take": 2
},
{
"id": "composer-mussorgsky",
"file": "composer-mussorgsky.m4a",
"class": "composer",
"sentence": "This composer is called Modest Mussorgsky.",
"take": 2
},
{
"id": "composer-rimsky-korsakov",
"file": "composer-rimsky-korsakov.m4a",
"class": "composer",
"sentence": "This composer is called Nikolai Rimsky-Korsakov.",
"take": 2
},
{
"id": "composer-strauss",
"file": "composer-strauss.m4a",
"class": "composer",
"sentence": "This composer is called Johann Strauss the Second.",
"take": 2
},
{
"id": "composer-bizet",
"file": "composer-bizet.m4a",
"class": "composer",
"sentence": "This composer is called Georges Bizet.",
"take": 2
},
{
"id": "composer-rossini",
"file": "composer-rossini.m4a",
"class": "composer",
"sentence": "This composer is called Gioachino Rossini.",
"take": 2
},
{
"id": "composer-debussy",
"file": "composer-debussy.m4a",
"class": "composer",
"sentence": "This composer is called Claude Debussy.",
"take": 2
},
{
"id": "composer-satie",
"file": "composer-satie.m4a",
"class": "composer",
"sentence": "This composer is called Erik Satie.",
"take": 2
},
{
"id": "composer-joplin",
"file": "composer-joplin.m4a",
"class": "composer",
"sentence": "This composer is called Scott Joplin.",
"take": 2
},
{
"id": "composer-holst",
"file": "composer-holst.m4a",
"class": "composer",
"sentence": "This composer is called Gustav Holst.",
"take": 2
}
];
