// Generated by tools/build-mapbridge-manifest.py from the owner-approved curation.
// Approved spoken text ships with the UI so visible words exactly match each clip.
export const MAP_BRIDGE_CLIP_TEXTS = {"mapbridge-intro": "Listen to one tune. Then tap its shape.", "mapbridge-correct": "Yes. That shape follows this tune.", "mapbridge-try-again": "Not that one yet. Listen once more, then try another shape.", "mapbridge-complete": "You matched every tune to its shape."};
export const MAP_BRIDGE_CLIP_ORDER = ["mapbridge-intro", "mapbridge-correct", "mapbridge-try-again", "mapbridge-complete"];
