/* SPELLING EXAM ENGINE — data and scheduling stay deliberately plain/testable. */
const SETS=[
['bat','pig','pot','man','van'],['fan','hat','top','bin','mat'],['dog','pan','hen','cat','map'],
['eye','ear','nose','arm','leg'],['hair','hand','face','mouth','foot'],['father','mother','son','brother','sister'],
['two','four','six','seven','nine'],['ten','eleven','fifteen','sixteen','twenty'],['bag','pencil','ruler','book','pen'],
['mop','broom','door','bin','window'],['tiger','fish','parrot','duck','rabbit'],['monkey','lion','snake','cow','bird']];
const ACCENTS=['us','uk','au'], STORE='spelling-exam-progress-v1', SESSION='spelling-exam-session-v1';
const $=s=>document.querySelector(s), app=$('#app');
let db=load(STORE,{words:{}}), sessionSeen=new Set(), state={screen:'home',mode:'practice',queue:[],i:0,typed:'',attempts:0,hinted:false,accent:'us',answers:[],locked:false,showWord:false};
function load(k,f){try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}} function save(){localStorage.setItem(STORE,JSON.stringify(db))}
function rec(word){return db.words[word]||(db.words[word]={correctUnassisted:0,incorrect:0,hintsUsed:0,lastPracticedAt:0,lastSession:'',accentIndex:0,accentOrder:[],accents:{us:{correct:0,incorrect:0},uk:{correct:0,incorrect:0},au:{correct:0,incorrect:0}}})}
function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function accentFor(word){const r=rec(word);if(!r.accentOrder.length){let block=shuffle(ACCENTS);if(r.lastAccent===block[0])block.push(block.shift());r.accentOrder=block}const a=r.accentOrder.shift();r.lastAccent=a;save();return a}
function all(){return SETS.flatMap((words,i)=>words.map(word=>({word,set:i+1}))) }
function mastery(word){const r=rec(word);if(r.correctUnassisted>=3&&(r.correctSessions||[]).length>=2)return'MASTERED';if(r.correctUnassisted>=2)return'ALMOST';if(r.correctUnassisted||r.incorrect)return'LEARNING';return'NEW'}
function sessionId(){let id=sessionStorage.getItem(SESSION);if(!id){id=Date.now().toString(36);sessionStorage.setItem(SESSION,id)}return id}
function priority(x){const r=rec(x.word);return (r.incorrect*5+r.hintsUsed*4+(r.correctUnassisted?0:8))-(r.correctUnassisted*2)+(r.lastPracticedAt?Math.min(5,(Date.now()-r.lastPracticedAt)/864e5):6)+Math.random()}
function home(){state.screen='home';app.innerHTML=`<section class="hero"><div class="mascot">📝✨</div><h1>Spelling Exam</h1><p>See it. Hear it. Spell it.</p></section><section class="menu"><button data-go="practice"><strong>Practice Now</strong><small>Start with words that need you most</small></button><button data-go="exam"><strong>Mock Exam</strong><small>Five words, results at the end</small></button><button data-go="weak"><strong>Weak Words</strong><small>Practise tricky words again</small></button><button data-go="sets"><strong>Word Sets 1–12</strong><small>Choose the school list</small></button><button data-go="learn"><strong>Learn Words</strong><small>Look, listen, then copy</small></button></section>`;bindNav()}
function bindNav(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>route(b.dataset.go))}
function route(go){if(go==='practice')start('practice',shuffle(all()).sort((a,b)=>priority(b)-priority(a)).slice(0,10));if(go==='weak'){const q=all().filter(x=>rec(x.word).incorrect||rec(x.word).hintsUsed).sort((a,b)=>priority(b)-priority(a));start('practice',(q.length?q:all()).slice(0,10))}if(go==='sets')chooseSets('practice');if(go==='learn')chooseSets('learn');if(go==='exam')examMenu()}
function headerBar(title,extra=''){return `<header class="top"><button class="back" aria-label="Back">←</button><h1>${title}</h1>${extra}</header>`}
function wireBack(fn=home){$('.back').onclick=fn}
function chooseSets(mode,examVariant=''){app.innerHTML=headerBar(mode==='learn'?'Learn Words':'Choose a word set')+`<section class="sets">${SETS.map((w,i)=>{const m=w.filter(x=>mastery(x)==='MASTERED').length;return`<button class="set" data-set="${i}"><b>WORDS ${i+1}</b><span>${m} / 5 mastered</span></button>`}).join('')}</section>`;wireBack(mode==='learn'?home:examVariant?examMenu:home);document.querySelectorAll('.set').forEach(b=>b.onclick=()=>start(mode,SETS[+b.dataset.set].map(word=>({word,set:+b.dataset.set+1})),examVariant))}
function examMenu(){app.innerHTML=headerBar('Mock Exam')+`<section class="menu"><button data-variant="picture"><strong>Picture-assisted</strong><small>See the picture and hear the word</small></button><button data-variant="dictation"><strong>Pure dictation</strong><small>Hear the word, without a picture</small></button></section>`;wireBack();document.querySelectorAll('[data-variant]').forEach(b=>b.onclick=()=>chooseSets('exam',b.dataset.variant))}
function start(mode,queue,variant=''){state={screen:'question',mode,variant,queue:shuffle(queue),i:0,typed:'',attempts:0,hinted:false,accent:'us',answers:[],locked:false,showWord:mode==='learn'};next(true)}
function current(){return state.queue[state.i]}
function next(first=false){if(state.i>=state.queue.length)return results();state.typed='';state.attempts=0;state.hinted=false;state.locked=false;state.showWord=state.mode==='learn';state.accent=accentFor(current().word);renderQuestion();setTimeout(playWord,first?450:250)}
function visual(word){return`<div class="picture"><img src="assets/words/${word}.webp" alt="" draggable="false"></div>`}
function renderQuestion(){const q=current(),hidePicture=state.mode==='exam'&&state.variant==='dictation';app.innerHTML=headerBar(state.mode==='exam'?'Mock Exam':state.mode==='learn'?'Learn Words':'Practice',`<span class="pill">${state.i+1} / ${state.queue.length}</span>`)+`<section class="stage"><div class="card">${hidePicture?'<div class="picture">🎧</div>':visual(q.word)}<button class="sound" aria-label="Replay word">🔊</button>${state.showWord?`<div class="word-reveal">${q.word}</div>`:'<p class="prompt">Listen and spell the word</p>'}<div class="slots">${q.word.split('').map((_,i)=>`<span class="slot">${state.typed[i]||''}</span>`).join('')}</div><div class="feedback"></div></div><div>${keyboard()}</div></section>`;wireBack(()=>state.mode==='exam'?examMenu():home());$('.sound').onclick=playWord;wireKeys()}
function keyboard(){return`<div class="keyboard" aria-label="On-screen keyboard">${['qwertyuiop','asdfghjkl','zxcvbnm'].map(r=>`<div class="row">${[...r].map(x=>`<button class="key" data-key="${x}">${x}</button>`).join('')}</div>`).join('')}<div class="row"><button class="key wide" data-key="clear">clear</button><button class="key wide" data-key="back">⌫</button><button class="key wide" data-key="enter">check</button></div></div>`}
function wireKeys(){document.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>key(b.dataset.key));window.onkeydown=e=>{if(/^[a-z]$/i.test(e.key))key(e.key.toLowerCase());else if(e.key==='Backspace')key('back');else if(e.key==='Enter')key('enter')}}
function key(k){if(state.locked)return;const w=current().word;if(k==='back')state.typed=state.typed.slice(0,-1);else if(k==='clear')state.typed='';else if(k==='enter'){check();return}else if(state.typed.length<w.length)state.typed+=k;document.querySelectorAll('.slot').forEach((s,i)=>s.textContent=state.typed[i]||'');if(state.typed.length===w.length)check()}
function feedback(text,cls){$('.feedback').textContent=text;$('.feedback').className='feedback '+cls}
function check(){if(!state.typed)return;const q=current(),r=rec(q.word),ok=state.typed.toLowerCase()===q.word;if(state.mode==='exam'){state.answers.push({word:q.word,typed:state.typed,ok,accent:state.accent});state.locked=true;state.i++;setTimeout(next,250);return}if(ok){state.locked=true;r.lastPracticedAt=Date.now();r.accents[state.accent].correct++;if(!state.hinted&&state.attempts===0&&!sessionSeen.has(q.word)){r.correctUnassisted++;r.correctSessions=[...new Set([...(r.correctSessions||[]),sessionId()])]}r.lastSession=sessionId();sessionSeen.add(q.word);save();feedback('You spelled it! ⭐','good');chime(true);state.i++;setTimeout(next,750)}else{state.attempts++;r.incorrect++;r.accents[state.accent].incorrect++;r.lastPracticedAt=Date.now();if(state.attempts===2){state.hinted=true;r.hintsUsed++;state.typed=q.word[0];document.querySelectorAll('.slot').forEach((s,i)=>s.textContent=state.typed[i]||'');feedback(`Try again — it starts with “${q.word[0]}”.`,'try')}else if(state.attempts>=3){state.hinted=true;state.showWord=true;renderQuestion();feedback('Look carefully, then type the whole word.','try')}else{state.typed='';document.querySelectorAll('.slot').forEach(s=>s.textContent='');feedback('Not yet — listen and try again.','try');playWord()}save();chime(false)}}
let audio;function playWord(){const {word}=current();if(audio)audio.pause();audio=new Audio(`assets/audio/${state.accent}/${word}.m4a`);audio.play().catch(()=>feedback('Tap 🔊 to hear the word.','muted'))}
function spellLetters(){let i=0;const letters=current().word.split('');function one(){if(i>=letters.length)return;const a=new Audio(`assets/audio/letters/${letters[i++]}.m4a`);a.onended=one;a.play().catch(()=>{});}one()}
function chime(ok){const C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=ok?660:180;g.gain.setValueAtTime(.08,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.18);o.start();o.stop(c.currentTime+.2)}
function results(){window.onkeydown=null;if(state.mode!=='exam'){home();return}const score=state.answers.filter(x=>x.ok).length;state.answers.forEach(a=>{const r=rec(a.word);r.lastPracticedAt=Date.now();if(a.ok){r.correctUnassisted++;r.correctSessions=[...new Set([...(r.correctSessions||[]),sessionId()])];r.accents[a.accent].correct++}else{r.incorrect++;r.accents[a.accent].incorrect++}});save();app.innerHTML=headerBar('Your results')+`<section class="card results"><div class="word-reveal">${score} / ${state.answers.length}</div>${state.answers.map(a=>`<div class="result"><b>${a.ok?'✓':'✗'} ${a.word}</b><span>${a.ok?'correct':`you typed: ${a.typed||'—'}`}</span></div>`).join('')}<div class="actions"><button class="primary mistakes">Practice mistakes</button><button class="secondary done">Done</button></div></section>`;wireBack(home);$('.done').onclick=home;$('.mistakes').onclick=()=>{const q=state.answers.filter(x=>!x.ok).map(x=>all().find(y=>y.word===x.word));start('practice',q.length?q:state.queue)}}
home();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');
