/* SPELLING EXAM ENGINE — data and scheduling stay deliberately plain/testable. */
/* Mascot: hand-drawn inline SVG (princess-crown unicorn), so no asset file ships for it. */
const MASCOT=`<svg viewBox="0 0 320 240" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="horn" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#ffe08a"/><stop offset="1" stop-color="#f6ad3d"/></linearGradient></defs><path d="M226,84 Q292,116 268,182 Q256,212 222,216 Q246,180 236,152 Q228,120 210,108 Z" fill="#c4b5fd"/><path d="M228,96 Q282,124 260,176 Q250,198 228,204 Q246,174 238,148 Q232,120 216,112 Z" fill="#e879f9"/><path d="M94,84 Q48,112 62,158 Q70,180 96,186 Q80,146 102,114 Z" fill="#f9a8d4"/><path d="M100,66 Q86,12 118,32 Q130,48 120,70 Z" fill="#fffdfb"/><path d="M104,60 Q96,28 116,40 Q122,52 116,64 Z" fill="#ffc9de"/><path d="M220,66 Q234,12 202,32 Q190,48 200,70 Z" fill="#fffdfb"/><path d="M216,60 Q224,28 204,40 Q198,52 204,64 Z" fill="#ffc9de"/><polygon points="160,16 145,80 175,80" fill="url(#horn)"/><path d="M150,62 Q160,69 170,62" stroke="#dba53d" stroke-width="5" fill="none" stroke-linecap="round"/><path d="M153,44 Q160,50 167,44" stroke="#dba53d" stroke-width="5" fill="none" stroke-linecap="round"/><ellipse cx="160" cy="138" rx="80" ry="72" fill="#fffdfb"/><ellipse cx="160" cy="176" rx="46" ry="28" fill="#ffedf4"/><path d="M128,86 Q140,58 162,64 Q186,58 194,86 Q178,72 161,78 Q144,72 128,86 Z" fill="#f9a8d4"/><g transform="translate(206,30) rotate(14)"><path d="M0,28 4,6 13,18 22,2 31,18 40,6 44,28 Z" fill="url(#horn)"/><path d="M0,28 h44 v8 a4,4 0 0 1 -4,4 H4 a4,4 0 0 1 -4,-4 Z" fill="#f2b64b"/><circle cx="10" cy="34" r="3.5" fill="#f44fa0"/><circle cx="22" cy="34" r="3.5" fill="#f44fa0"/><circle cx="34" cy="34" r="3.5" fill="#f44fa0"/></g><ellipse cx="108" cy="164" rx="10" ry="6" fill="#ffc3dd" opacity=".85"/><ellipse cx="212" cy="164" rx="10" ry="6" fill="#ffc3dd" opacity=".85"/><circle cx="130" cy="140" r="11" fill="#3b2340"/><circle cx="126" cy="136" r="4" fill="#fff"/><circle cx="134" cy="145" r="2" fill="#fff"/><circle cx="190" cy="140" r="11" fill="#3b2340"/><circle cx="186" cy="136" r="4" fill="#fff"/><circle cx="194" cy="145" r="2" fill="#fff"/><ellipse cx="149" cy="178" rx="3.5" ry="5" fill="#d98aa8"/><ellipse cx="171" cy="178" rx="3.5" ry="5" fill="#d98aa8"/><path d="M151,192 Q160,200 169,192" stroke="#b5688c" stroke-width="4.5" fill="none" stroke-linecap="round"/><path d="M0,-13 Q2.5,-2.5 13,0 Q2.5,2.5 0,13 Q-2.5,2.5 -13,0 Q-2.5,-2.5 0,-13 Z" transform="translate(54,54)" fill="#fcd34d"/><path d="M0,-13 Q2.5,-2.5 13,0 Q2.5,2.5 0,13 Q-2.5,2.5 -13,0 Q-2.5,-2.5 0,-13 Z" transform="translate(268,70) scale(.8)" fill="#f472b6"/><path d="M0,-13 Q2.5,-2.5 13,0 Q2.5,2.5 0,13 Q-2.5,2.5 -13,0 Q-2.5,-2.5 0,-13 Z" transform="translate(70,196) scale(.75)" fill="#c4b5fd"/><path d="M0,-13 Q2.5,-2.5 13,0 Q2.5,2.5 0,13 Q-2.5,2.5 -13,0 Q-2.5,-2.5 0,-13 Z" transform="translate(246,222) scale(.9)" fill="#fcd34d"/></svg>`;
const SETS=[
['bat','pig','pot','man','van'],['fan','hat','top','bin','mat'],['dog','pan','hen','cat','map'],
['eye','ear','nose','arm','leg'],['hair','hand','face','mouth','foot'],['father','mother','son','brother','sister'],
['two','four','six','seven','nine'],['ten','eleven','fifteen','sixteen','twenty'],['bag','pencil','ruler','book','pen'],
['mop','broom','door','bin','window'],['tiger','fish','parrot','duck','rabbit'],['monkey','lion','snake','cow','bird']];
const ACCENTS=['us','uk','au'], STORE='spelling-exam-progress-v1', SESSION='spelling-exam-session-v1';
const $=s=>document.querySelector(s), app=$('#app');
let db=load(STORE,{words:{}}), sessionSeen=new Set(), state={screen:'home',mode:'practice',queue:[],i:0,typed:'',attempts:0,hinted:false,accent:'us',answers:[],locked:false,showWord:false};
function load(k,f){try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}} function save(){localStorage.setItem(STORE,JSON.stringify(db))}
function rec(word){return db.words[word]||(db.words[word]={correctUnassisted:0,incorrect:0,hintsUsed:0,lastPracticedAt:0,lastSession:'',accentIndex:0,accentOrder:[],accents:{us:{correct:0,incorrect:0},uk:{correct:0,incorrect:0},au:{correct:0,incorrect:0}}})}
function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function accentFor(word){const r=rec(word);if(!r.accentOrder.length){let block=shuffle(ACCENTS);if(r.lastAccent===block[0])block.push(block.shift());r.accentOrder=block}const a=r.accentOrder.shift();r.lastAccent=a;save();return a}
function all(){return SETS.flatMap((words,i)=>words.map(word=>({word,set:i+1}))) }
function mastery(word){const r=rec(word);if(r.correctUnassisted>=3&&(r.correctSessions||[]).length>=2)return'MASTERED';if(r.correctUnassisted>=2)return'ALMOST';if(r.correctUnassisted||r.incorrect)return'LEARNING';return'NEW'}
function sessionId(){let id=sessionStorage.getItem(SESSION);if(!id){id=Date.now().toString(36);sessionStorage.setItem(SESSION,id)}return id}
function priority(x){const r=rec(x.word);return (r.incorrect*5+r.hintsUsed*4+(r.correctUnassisted?0:8))-(r.correctUnassisted*2)+(r.lastPracticedAt?Math.min(5,(Date.now()-r.lastPracticedAt)/864e5):6)+Math.random()}
function home(){state.screen='home';app.innerHTML=`<section class="hero"><div class="mascot" aria-hidden="true">${MASCOT}</div><h1>Spelling Exam</h1><p>See it. Hear it. Spell it.</p></section><section class="menu"><button data-go="practice"><strong>Practice Now</strong><small>Start with words that need you most</small></button><button data-go="exam"><strong>Mock Exam</strong><small>Five words, results at the end</small></button><button data-go="weak"><strong>Weak Words</strong><small>Practise tricky words again</small></button><button data-go="sets"><strong>Word Sets 1–12</strong><small>Choose the school list</small></button><button data-go="learn"><strong>Learn Words</strong><small>Look, listen, then copy</small></button></section>`;bindNav()}
function bindNav(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>route(b.dataset.go))}
function route(go){if(go==='practice')start('practice',shuffle(all()).sort((a,b)=>priority(b)-priority(a)).slice(0,10));if(go==='weak'){const q=all().filter(x=>rec(x.word).incorrect||rec(x.word).hintsUsed).sort((a,b)=>priority(b)-priority(a));start('practice',(q.length?q:all()).slice(0,10))}if(go==='sets')chooseSets('practice');if(go==='learn')chooseSets('learn');if(go==='exam')examMenu()}
function headerBar(title,extra=''){return `<header class="top"><button class="back" aria-label="Back">←</button><h1>${title}</h1>${extra}</header>`}
function wireBack(fn=home){$('.back').onclick=fn}
function chooseSets(mode,examVariant=''){app.innerHTML=headerBar(mode==='learn'?'Learn Words':'Choose a word set')+`<section class="sets">${SETS.map((w,i)=>{const m=w.filter(x=>mastery(x)==='MASTERED').length;return`<button class="set" data-set="${i}"><b>WORDS ${i+1}</b><span>${m} / 5 mastered</span></button>`}).join('')}</section>`;wireBack(mode==='learn'?home:examVariant?examMenu:home);document.querySelectorAll('.set').forEach(b=>b.onclick=()=>start(mode,SETS[+b.dataset.set].map(word=>({word,set:+b.dataset.set+1})),examVariant))}
function examMenu(){app.innerHTML=headerBar('Mock Exam')+`<section class="menu"><button data-variant="picture"><strong>Picture-assisted</strong><small>See the picture and hear the word</small></button><button data-variant="dictation"><strong>Pure dictation</strong><small>Hear the word, without a picture</small></button></section>`;wireBack();document.querySelectorAll('[data-variant]').forEach(b=>b.onclick=()=>chooseSets('exam',b.dataset.variant))}
function start(mode,queue,variant=''){state={screen:'question',mode,variant,queue:shuffle(queue),i:0,typed:'',attempts:0,hinted:false,accent:'us',answers:[],locked:false,showWord:mode==='learn'};next(true)}
function current(){return state.queue[state.i]}
function next(first=false){if(state.i>=state.queue.length)return results();state.typed='';state.attempts=0;state.hinted=false;state.locked=false;state.showWord=state.mode==='learn';state.accent=accentFor(current().word);renderQuestion();setTimeout(playWord,first?450:250)}
function visual(word){return`<div class="picture"><img src="assets/words/${word}.webp" alt="" draggable="false"></div>`}
function renderQuestion(){const q=current(),hidePicture=state.mode==='exam'&&state.variant==='dictation';app.innerHTML=headerBar(state.mode==='exam'?'Mock Exam':state.mode==='learn'?'Learn Words':'Practice',`<span class="pill">${state.i+1} / ${state.queue.length}</span>`)+`<section class="stage"><div class="card">${hidePicture?'<div class="picture">🎧</div>':visual(q.word)}<button class="sound" aria-label="Replay word">🔊</button>${state.showWord?`<div class="word-reveal">${q.word}</div>`:'<p class="prompt">Listen and spell the word</p>'}<div class="slots">${q.word.split('').map((_,i)=>`<span class="slot">${state.typed[i]||''}</span>`).join('')}</div><div class="feedback"></div></div><div>${keyboard()}</div></section>`;wireBack(()=>state.mode==='exam'?examMenu():home());$('.sound').onclick=playWord;wireKeys()}
function keyboard(){return`<div class="keyboard" aria-label="On-screen keyboard">${['qwertyuiop','asdfghjkl','zxcvbnm'].map(r=>`<div class="row">${[...r].map(x=>`<button class="key" data-key="${x}">${x}</button>`).join('')}</div>`).join('')}<div class="row"><button class="key wide" data-key="clear">clear</button><button class="key wide" data-key="back">⌫</button><button class="key wide" data-key="enter">check</button></div></div>`}
function wireKeys(){document.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>key(b.dataset.key));window.onkeydown=e=>{if(/^[a-z]$/i.test(e.key))key(e.key.toLowerCase());else if(e.key==='Backspace')key('back');else if(e.key==='Enter')key('enter')}}
function key(k){if(state.locked)return;const w=current().word;if(k==='back')state.typed=state.typed.slice(0,-1);else if(k==='clear')state.typed='';else if(k==='enter'){check();return}else if(state.typed.length<w.length)state.typed+=k;document.querySelectorAll('.slot').forEach((s,i)=>s.textContent=state.typed[i]||'');if(state.typed.length===w.length)check()}
function feedback(text,cls){$('.feedback').textContent=text;$('.feedback').className='feedback '+cls}
function check(){if(!state.typed)return;const q=current(),r=rec(q.word),ok=state.typed.toLowerCase()===q.word;if(state.mode==='exam'){state.answers.push({word:q.word,typed:state.typed,ok,accent:state.accent});state.locked=true;state.i++;setTimeout(next,250);return}if(ok){state.locked=true;r.lastPracticedAt=Date.now();r.accents[state.accent].correct++;if(!state.hinted&&state.attempts===0&&!sessionSeen.has(q.word)){r.correctUnassisted++;r.correctSessions=[...new Set([...(r.correctSessions||[]),sessionId()])]}r.lastSession=sessionId();sessionSeen.add(q.word);save();feedback('You spelled it! ⭐','good');celebrate();const slots=$('.slots');if(slots)slots.classList.add('win');chime(true);state.i++;setTimeout(next,750)}else{state.attempts++;r.incorrect++;r.accents[state.accent].incorrect++;r.lastPracticedAt=Date.now();if(state.attempts===2){state.hinted=true;r.hintsUsed++;state.typed=q.word[0];document.querySelectorAll('.slot').forEach((s,i)=>s.textContent=state.typed[i]||'');feedback(`Try again — it starts with “${q.word[0]}”.`,'try')}else if(state.attempts>=3){state.hinted=true;state.showWord=true;renderQuestion();feedback('Look carefully, then type the whole word.','try')}else{state.typed='';document.querySelectorAll('.slot').forEach(s=>s.textContent='');feedback('Not yet — listen and try again.','try');playWord()}save();chime(false)}}
let audio;function playWord(){const {word}=current();if(audio)audio.pause();audio=new Audio(`assets/audio/${state.accent}/${word}.m4a`);audio.play().catch(()=>feedback('Tap 🔊 to hear the word.','muted'))}
function spellLetters(){let i=0;const letters=current().word.split('');function one(){if(i>=letters.length)return;const a=new Audio(`assets/audio/letters/${letters[i++]}.m4a`);a.onended=one;a.play().catch(()=>{});}one()}
function chime(ok){const C=window.AudioContext||window.webkitAudioContext,c=new C();if(!ok){const o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=180;g.gain.setValueAtTime(.08,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.18);o.start();o.stop(c.currentTime+.2);return}/* three-note major arpeggio: the sound of getting it right */[523.25,659.25,783.99].forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+i*.09;o.type='triangle';o.connect(g);g.connect(c.destination);o.frequency.value=f;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.12,t+.02);g.gain.exponentialRampToValueAtTime(.001,t+.5);o.start(t);o.stop(t+.55)})}
function celebrate(){const host=document.createElement('div');host.className='celebration';host.setAttribute('aria-hidden','true');const BITS=['★','✦','♥','✧','✿'],COLORS=['#f06fb4','#9a55d6','#f6ad3d','#f472b6','#c4b5fd','#7ad0f0'];for(let i=0;i<44;i++){const s=document.createElement('span');s.className='confetti';s.textContent=BITS[i%BITS.length];s.style.left=(4+Math.random()*92)+'%';s.style.color=COLORS[i%COLORS.length];s.style.fontSize=(13+Math.random()*17)+'px';s.style.animationDuration=(.9+Math.random()*.9)+'s';s.style.animationDelay=(Math.random()*.25)+'s';host.appendChild(s)}document.body.appendChild(host);setTimeout(()=>host.remove(),2200)}
function results(){window.onkeydown=null;if(state.mode!=='exam'){home();return}const score=state.answers.filter(x=>x.ok).length;state.answers.forEach(a=>{const r=rec(a.word);r.lastPracticedAt=Date.now();if(a.ok){r.correctUnassisted++;r.correctSessions=[...new Set([...(r.correctSessions||[]),sessionId()])];r.accents[a.accent].correct++}else{r.incorrect++;r.accents[a.accent].incorrect++}});save();app.innerHTML=headerBar('Your results')+`<section class="card results"><div class="word-reveal">${score} / ${state.answers.length}</div>${state.answers.map(a=>`<div class="result"><b>${a.ok?'✓':'✗'} ${a.word}</b><span>${a.ok?'correct':`you typed: ${a.typed||'—'}`}</span></div>`).join('')}<div class="actions"><button class="primary mistakes">Practice mistakes</button><button class="secondary done">Done</button></div></section>`;wireBack(home);$('.done').onclick=home;$('.mistakes').onclick=()=>{const q=state.answers.filter(x=>!x.ok).map(x=>all().find(y=>y.word===x.word));start('practice',q.length?q:state.queue)}}
home();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');
